// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
)

const listAuditForEntity = `-- name: ListAuditForEntity :many
SELECT id, user_id, actor, at, "action", entity_type, entity_id, "before", "after", created_at, updated_at FROM audit_log
WHERE entity_type = ?1 AND entity_id = ?2
ORDER BY at DESC, id DESC
LIMIT ?3
`

type ListAuditForEntityParams struct {
	EntityType string
	EntityID   *int64
	PageSize   int64
}

func (q *Queries) ListAuditForEntity(ctx context.Context, arg ListAuditForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForEntity, arg.EntityType, arg.EntityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Actor,
			&i.At,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAudit = `-- name: RecordAudit :one

INSERT INTO audit_log (
    user_id, actor, at, action, entity_type, entity_id, before, after,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, actor, at, "action", entity_type, entity_id, "before", "after", created_at, updated_at
`

type RecordAuditParams struct {
	UserID     *int64
	Actor      string
	At         string
	Action     string
	EntityType string
	EntityID   *int64
	Before     string
	After      string
	CreatedAt  string
	UpdatedAt  string
}

// The audit log.
//
// Section 5.4 rests on this: an auto-applied receipt is only safe because the
// row it wrote can be found and undone. The write is inside the same
// transaction as the thing it records, so a log entry without its effect --
// or an effect without its entry -- is not a state this database can be in.
//
// There is no update and no delete on purpose. A record of what was done that
// can be edited is not one.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) RecordAudit(ctx context.Context, arg RecordAuditParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, recordAudit,
		arg.UserID,
		arg.Actor,
		arg.At,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Actor,
		&i.At,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
