// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    property_id, kind, title, original_filename, mime, size_bytes,
    sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?
)
RETURNING id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at
`

type CreateDocumentParams struct {
	PropertyID       *int64
	Kind             string
	Title            string
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	Sha256           string
	StoragePath      string
	ExtractedText    string
	UploadedBy       *int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.PropertyID,
		arg.Kind,
		arg.Title,
		arg.OriginalFilename,
		arg.Mime,
		arg.SizeBytes,
		arg.Sha256,
		arg.StoragePath,
		arg.ExtractedText,
		arg.UploadedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Kind,
		&i.Title,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.StoragePath,
		&i.ExtractedText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentLink = `-- name: CreateDocumentLink :one
INSERT INTO document_links (document_id, entity_type, entity_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, document_id, entity_type, entity_id, created_at, updated_at
`

type CreateDocumentLinkParams struct {
	DocumentID int64
	EntityType string
	EntityID   int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateDocumentLink(ctx context.Context, arg CreateDocumentLinkParams) (DocumentLink, error) {
	row := q.db.QueryRowContext(ctx, createDocumentLink,
		arg.DocumentID,
		arg.EntityType,
		arg.EntityID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DocumentLink
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentLink = `-- name: DeleteDocumentLink :execrows
DELETE FROM document_links
WHERE document_id = ?1
  AND entity_type = ?2
  AND entity_id = ?3
`

type DeleteDocumentLinkParams struct {
	DocumentID int64
	EntityType string
	EntityID   int64
}

func (q *Queries) DeleteDocumentLink(ctx context.Context, arg DeleteDocumentLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocumentLink, arg.DocumentID, arg.EntityType, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at FROM documents WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Kind,
		&i.Title,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.StoragePath,
		&i.ExtractedText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySHA = `-- name: GetDocumentBySHA :one
SELECT id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at FROM documents WHERE sha256 = ? LIMIT 1
`

// Content addressing means the hash is the identity: an upload that hashes to
// a row already on file is the same document, not a second copy.
func (q *Queries) GetDocumentBySHA(ctx context.Context, sha256 string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySHA, sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Kind,
		&i.Title,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.StoragePath,
		&i.ExtractedText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentLinks = `-- name: ListDocumentLinks :many

SELECT id, document_id, entity_type, entity_id, created_at, updated_at FROM document_links WHERE document_id = ? ORDER BY entity_type, entity_id
`

// Links ------------------------------------------------------------------
func (q *Queries) ListDocumentLinks(ctx context.Context, documentID int64) ([]DocumentLink, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentLinks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentLink{}
	for rows.Next() {
		var i DocumentLink
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByEntity = `-- name: ListDocumentsByEntity :many
SELECT documents.id, documents.property_id, documents.kind, documents.title, documents.original_filename, documents.mime, documents.size_bytes, documents.sha256, documents.storage_path, documents.extracted_text, documents.uploaded_by, documents.created_at, documents.updated_at
FROM documents
JOIN document_links ON document_links.document_id = documents.id
WHERE document_links.entity_type = ?1
  AND document_links.entity_id = ?2
ORDER BY documents.created_at DESC, documents.id DESC
`

type ListDocumentsByEntityParams struct {
	EntityType string
	EntityID   int64
}

// Everything filed against one entity: the receipts on a repair, the lease PDF
// on a lease.
func (q *Queries) ListDocumentsByEntity(ctx context.Context, arg ListDocumentsByEntityParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Kind,
			&i.Title,
			&i.OriginalFilename,
			&i.Mime,
			&i.SizeBytes,
			&i.Sha256,
			&i.StoragePath,
			&i.ExtractedText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByPropertyAfter = `-- name: ListDocumentsByPropertyAfter :many
SELECT id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at FROM documents
WHERE property_id = ?1
  AND (created_at < ?2
       OR (created_at = ?2 AND id < ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListDocumentsByPropertyAfterParams struct {
	PropertyID     *int64
	AfterCreatedAt string
	AfterID        int64
	PageSize       int64
}

func (q *Queries) ListDocumentsByPropertyAfter(ctx context.Context, arg ListDocumentsByPropertyAfterParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByPropertyAfter,
		arg.PropertyID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Kind,
			&i.Title,
			&i.OriginalFilename,
			&i.Mime,
			&i.SizeBytes,
			&i.Sha256,
			&i.StoragePath,
			&i.ExtractedText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByPropertyFirstPage = `-- name: ListDocumentsByPropertyFirstPage :many

SELECT id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at FROM documents
WHERE property_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListDocumentsByPropertyFirstPageParams struct {
	PropertyID *int64
	PageSize   int64
}

// Documents are listed newest first, so the keyset runs backwards over
// (created_at, id): created_at is not unique when two files land in the same
// second, and id breaks the tie.
func (q *Queries) ListDocumentsByPropertyFirstPage(ctx context.Context, arg ListDocumentsByPropertyFirstPageParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByPropertyFirstPage, arg.PropertyID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Kind,
			&i.Title,
			&i.OriginalFilename,
			&i.Mime,
			&i.SizeBytes,
			&i.Sha256,
			&i.StoragePath,
			&i.ExtractedText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
    property_id       = ?,
    kind              = ?,
    title             = ?,
    original_filename = ?,
    extracted_text    = ?,
    updated_at        = ?
WHERE id = ?
RETURNING id, property_id, kind, title, original_filename, mime, size_bytes, sha256, storage_path, extracted_text, uploaded_by, created_at, updated_at
`

type UpdateDocumentParams struct {
	PropertyID       *int64
	Kind             string
	Title            string
	OriginalFilename string
	ExtractedText    string
	UpdatedAt        string
	ID               int64
}

// Every column is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.PropertyID,
		arg.Kind,
		arg.Title,
		arg.OriginalFilename,
		arg.ExtractedText,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Kind,
		&i.Title,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.StoragePath,
		&i.ExtractedText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
