// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package sqlc

import (
	"context"
)

const countEmailMessagesByStatus = `-- name: CountEmailMessagesByStatus :many
SELECT status, COUNT(*) AS count FROM email_messages GROUP BY status
`

type CountEmailMessagesByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountEmailMessagesByStatus(ctx context.Context) ([]CountEmailMessagesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countEmailMessagesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEmailMessagesByStatusRow{}
	for rows.Next() {
		var i CountEmailMessagesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEmailAttachment = `-- name: CreateEmailAttachment :one
INSERT INTO email_attachments (
    email_message_id, part_id, filename, mime, size_bytes, document_id,
    skipped_reason, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, email_message_id, part_id, filename, mime, size_bytes, document_id, skipped_reason, created_at, updated_at
`

type CreateEmailAttachmentParams struct {
	EmailMessageID int64
	PartID         string
	Filename       string
	Mime           string
	SizeBytes      int64
	DocumentID     *int64
	SkippedReason  string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreateEmailAttachment(ctx context.Context, arg CreateEmailAttachmentParams) (EmailAttachment, error) {
	row := q.db.QueryRowContext(ctx, createEmailAttachment,
		arg.EmailMessageID,
		arg.PartID,
		arg.Filename,
		arg.Mime,
		arg.SizeBytes,
		arg.DocumentID,
		arg.SkippedReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.PartID,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.DocumentID,
		&i.SkippedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailMessage = `-- name: CreateEmailMessage :one
INSERT INTO email_messages (
    gmail_message_id, thread_id, from_addr, to_addr, subject, received_at,
    snippet, raw_path, status, error, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?
)
RETURNING id, gmail_message_id, thread_id, from_addr, to_addr, subject, received_at, snippet, raw_path, status, error, created_at, updated_at
`

type CreateEmailMessageParams struct {
	GmailMessageID string
	ThreadID       string
	FromAddr       string
	ToAddr         string
	Subject        string
	ReceivedAt     string
	Snippet        string
	RawPath        string
	Status         string
	Error          string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRowContext(ctx, createEmailMessage,
		arg.GmailMessageID,
		arg.ThreadID,
		arg.FromAddr,
		arg.ToAddr,
		arg.Subject,
		arg.ReceivedAt,
		arg.Snippet,
		arg.RawPath,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.GmailMessageID,
		&i.ThreadID,
		&i.FromAddr,
		&i.ToAddr,
		&i.Subject,
		&i.ReceivedAt,
		&i.Snippet,
		&i.RawPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailMessage = `-- name: GetEmailMessage :one

SELECT id, gmail_message_id, thread_id, from_addr, to_addr, subject, received_at, snippet, raw_path, status, error, created_at, updated_at FROM email_messages WHERE id = ? LIMIT 1
`

// What arrived, and what came attached to it.
//
// gmail_message_id is the idempotency key for the whole pipeline. The read
// before the insert is the same shape the document upload uses against sha256:
// a message already on file is the same message, not a second copy of it.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) GetEmailMessage(ctx context.Context, id int64) (EmailMessage, error) {
	row := q.db.QueryRowContext(ctx, getEmailMessage, id)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.GmailMessageID,
		&i.ThreadID,
		&i.FromAddr,
		&i.ToAddr,
		&i.Subject,
		&i.ReceivedAt,
		&i.Snippet,
		&i.RawPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailMessageByGmailID = `-- name: GetEmailMessageByGmailID :one
SELECT id, gmail_message_id, thread_id, from_addr, to_addr, subject, received_at, snippet, raw_path, status, error, created_at, updated_at FROM email_messages WHERE gmail_message_id = ? LIMIT 1
`

func (q *Queries) GetEmailMessageByGmailID(ctx context.Context, gmailMessageID string) (EmailMessage, error) {
	row := q.db.QueryRowContext(ctx, getEmailMessageByGmailID, gmailMessageID)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.GmailMessageID,
		&i.ThreadID,
		&i.FromAddr,
		&i.ToAddr,
		&i.Subject,
		&i.ReceivedAt,
		&i.Snippet,
		&i.RawPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailAttachments = `-- name: ListEmailAttachments :many

SELECT id, email_message_id, part_id, filename, mime, size_bytes, document_id, skipped_reason, created_at, updated_at FROM email_attachments
WHERE email_message_id = ?
ORDER BY id
`

// Attachments --------------------------------------------------------------
func (q *Queries) ListEmailAttachments(ctx context.Context, emailMessageID int64) ([]EmailAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listEmailAttachments, emailMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAttachment{}
	for rows.Next() {
		var i EmailAttachment
		if err := rows.Scan(
			&i.ID,
			&i.EmailMessageID,
			&i.PartID,
			&i.Filename,
			&i.Mime,
			&i.SizeBytes,
			&i.DocumentID,
			&i.SkippedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailMessagesAfter = `-- name: ListEmailMessagesAfter :many
SELECT id, gmail_message_id, thread_id, from_addr, to_addr, subject, received_at, snippet, raw_path, status, error, created_at, updated_at FROM email_messages
WHERE (received_at < ?1
       OR (received_at = ?1 AND id < ?2))
ORDER BY received_at DESC, id DESC
LIMIT ?3
`

type ListEmailMessagesAfterParams struct {
	AfterReceivedAt string
	AfterID         int64
	PageSize        int64
}

func (q *Queries) ListEmailMessagesAfter(ctx context.Context, arg ListEmailMessagesAfterParams) ([]EmailMessage, error) {
	rows, err := q.db.QueryContext(ctx, listEmailMessagesAfter, arg.AfterReceivedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailMessage{}
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.GmailMessageID,
			&i.ThreadID,
			&i.FromAddr,
			&i.ToAddr,
			&i.Subject,
			&i.ReceivedAt,
			&i.Snippet,
			&i.RawPath,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailMessagesFirstPage = `-- name: ListEmailMessagesFirstPage :many
SELECT id, gmail_message_id, thread_id, from_addr, to_addr, subject, received_at, snippet, raw_path, status, error, created_at, updated_at FROM email_messages
ORDER BY received_at DESC, id DESC
LIMIT ?1
`

// The register, newest first. The keyset runs backwards over
// (received_at, id): two messages can share a second, and id breaks the tie.
func (q *Queries) ListEmailMessagesFirstPage(ctx context.Context, pageSize int64) ([]EmailMessage, error) {
	rows, err := q.db.QueryContext(ctx, listEmailMessagesFirstPage, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailMessage{}
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.GmailMessageID,
			&i.ThreadID,
			&i.FromAddr,
			&i.ToAddr,
			&i.Subject,
			&i.ReceivedAt,
			&i.Snippet,
			&i.RawPath,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailMessageStatus = `-- name: SetEmailMessageStatus :exec
UPDATE email_messages SET
    status     = ?1,
    error      = ?2,
    updated_at = ?3
WHERE id = ?4
`

type SetEmailMessageStatusParams struct {
	Status    string
	Error     string
	UpdatedAt string
	ID        int64
}

func (q *Queries) SetEmailMessageStatus(ctx context.Context, arg SetEmailMessageStatusParams) error {
	_, err := q.db.ExecContext(ctx, setEmailMessageStatus,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
