// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gmail.sql

package sqlc

import (
	"context"
)

const deleteGmailAccount = `-- name: DeleteGmailAccount :execrows
DELETE FROM gmail_account WHERE id = 1
`

func (q *Queries) DeleteGmailAccount(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGmailAccount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGmailAccount = `-- name: GetGmailAccount :one

SELECT id, address, refresh_token_enc, scopes, connected_at, history_id, watch_expires_at, last_sync_at, last_sync_count, last_error, status, created_at, updated_at FROM gmail_account WHERE id = 1 LIMIT 1
`

// The connected Gmail account: one row, id 1.
//
// The writes are narrow on purpose. Connecting replaces the whole row; a sync,
// a watch renewal, and a failure each touch only the columns they know about,
// so a sync that finishes while a renewal is in flight cannot roll back the
// watch expiry it never read.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) GetGmailAccount(ctx context.Context) (GmailAccount, error) {
	row := q.db.QueryRowContext(ctx, getGmailAccount)
	var i GmailAccount
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.RefreshTokenEnc,
		&i.Scopes,
		&i.ConnectedAt,
		&i.HistoryID,
		&i.WatchExpiresAt,
		&i.LastSyncAt,
		&i.LastSyncCount,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveGmailAccount = `-- name: SaveGmailAccount :one
INSERT INTO gmail_account (
    id, address, refresh_token_enc, scopes, connected_at, history_id,
    watch_expires_at, last_sync_at, last_sync_count, last_error, status,
    created_at, updated_at
) VALUES (
    1, ?, ?, ?, ?, ?,
    NULL, NULL, 0, '', 'connected',
    ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    address           = excluded.address,
    refresh_token_enc = excluded.refresh_token_enc,
    scopes            = excluded.scopes,
    connected_at      = excluded.connected_at,
    history_id        = excluded.history_id,
    watch_expires_at  = NULL,
    last_sync_at      = NULL,
    last_sync_count   = 0,
    last_error        = '',
    status            = 'connected',
    updated_at        = excluded.updated_at
RETURNING id, address, refresh_token_enc, scopes, connected_at, history_id, watch_expires_at, last_sync_at, last_sync_count, last_error, status, created_at, updated_at
`

type SaveGmailAccountParams struct {
	Address         string
	RefreshTokenEnc string
	Scopes          string
	ConnectedAt     string
	HistoryID       string
	CreatedAt       string
	UpdatedAt       string
}

// Connecting, or reconnecting a different mailbox. The cursor comes from the
// profile at connect time, so the first sync does not walk history that
// predates the grant.
func (q *Queries) SaveGmailAccount(ctx context.Context, arg SaveGmailAccountParams) (GmailAccount, error) {
	row := q.db.QueryRowContext(ctx, saveGmailAccount,
		arg.Address,
		arg.RefreshTokenEnc,
		arg.Scopes,
		arg.ConnectedAt,
		arg.HistoryID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GmailAccount
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.RefreshTokenEnc,
		&i.Scopes,
		&i.ConnectedAt,
		&i.HistoryID,
		&i.WatchExpiresAt,
		&i.LastSyncAt,
		&i.LastSyncCount,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGmailCursor = `-- name: SetGmailCursor :exec
UPDATE gmail_account SET
    history_id      = ?1,
    last_sync_at    = CAST(?2 AS TEXT),
    last_sync_count = ?3,
    last_error      = '',
    status          = 'connected',
    updated_at      = ?4
WHERE id = 1
`

type SetGmailCursorParams struct {
	HistoryID     string
	LastSyncAt    string
	LastSyncCount int64
	UpdatedAt     string
}

// A sync always happened at a time, so last_sync_at is cast: the column is
// nullable, and without the cast sqlc hands the caller a *string for a value it
// can never not have. watch_expires_at below keeps its pointer, because a watch
// that failed to register genuinely has no expiry.
func (q *Queries) SetGmailCursor(ctx context.Context, arg SetGmailCursorParams) error {
	_, err := q.db.ExecContext(ctx, setGmailCursor,
		arg.HistoryID,
		arg.LastSyncAt,
		arg.LastSyncCount,
		arg.UpdatedAt,
	)
	return err
}

const setGmailRefreshToken = `-- name: SetGmailRefreshToken :exec
UPDATE gmail_account SET
    refresh_token_enc = ?1,
    updated_at        = ?2
WHERE id = 1
`

type SetGmailRefreshTokenParams struct {
	RefreshTokenEnc string
	UpdatedAt       string
}

// Google rotates a refresh token occasionally. Losing the new one means the
// grant dies at the next refresh, silently, days later.
func (q *Queries) SetGmailRefreshToken(ctx context.Context, arg SetGmailRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, setGmailRefreshToken, arg.RefreshTokenEnc, arg.UpdatedAt)
	return err
}

const setGmailStatus = `-- name: SetGmailStatus :exec
UPDATE gmail_account SET
    status     = ?1,
    last_error = ?2,
    updated_at = ?3
WHERE id = 1
`

type SetGmailStatusParams struct {
	Status    string
	LastError string
	UpdatedAt string
}

// degraded is recoverable and revoked is not, but neither is fatal to the
// process: the last known state stays on the card, annotated with what went
// wrong (docs/DESIGN.md section 6.1 makes the same argument for valuations).
func (q *Queries) SetGmailStatus(ctx context.Context, arg SetGmailStatusParams) error {
	_, err := q.db.ExecContext(ctx, setGmailStatus, arg.Status, arg.LastError, arg.UpdatedAt)
	return err
}

const setGmailWatch = `-- name: SetGmailWatch :exec
UPDATE gmail_account SET
    watch_expires_at = ?1,
    updated_at       = ?2
WHERE id = 1
`

type SetGmailWatchParams struct {
	WatchExpiresAt *string
	UpdatedAt      string
}

func (q *Queries) SetGmailWatch(ctx context.Context, arg SetGmailWatchParams) error {
	_, err := q.db.ExecContext(ctx, setGmailWatch, arg.WatchExpiresAt, arg.UpdatedAt)
	return err
}
