// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insurance.sql

package sqlc

import (
	"context"

	"github.com/farrellm/rental-bot/internal/domain"
)

const createInsurancePolicy = `-- name: CreateInsurancePolicy :one
INSERT INTO insurance_policies (
    property_id, carrier, policy_number_enc, type, agent_name, agent_phone,
    agent_email, effective_date, expiration_date, annual_premium_cents,
    dwelling_coverage_cents, liability_coverage_cents, deductible_cents,
    document_id, notes, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?
)
RETURNING id, property_id, carrier, policy_number_enc, type, agent_name, agent_phone, agent_email, effective_date, expiration_date, annual_premium_cents, dwelling_coverage_cents, liability_coverage_cents, deductible_cents, document_id, notes, created_at, updated_at
`

type CreateInsurancePolicyParams struct {
	PropertyID             int64
	Carrier                string
	PolicyNumberEnc        string
	Type                   string
	AgentName              string
	AgentPhone             string
	AgentEmail             string
	EffectiveDate          *string
	ExpirationDate         *string
	AnnualPremiumCents     *domain.Money
	DwellingCoverageCents  *domain.Money
	LiabilityCoverageCents *domain.Money
	DeductibleCents        *domain.Money
	DocumentID             *int64
	Notes                  string
	CreatedAt              string
	UpdatedAt              string
}

func (q *Queries) CreateInsurancePolicy(ctx context.Context, arg CreateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRowContext(ctx, createInsurancePolicy,
		arg.PropertyID,
		arg.Carrier,
		arg.PolicyNumberEnc,
		arg.Type,
		arg.AgentName,
		arg.AgentPhone,
		arg.AgentEmail,
		arg.EffectiveDate,
		arg.ExpirationDate,
		arg.AnnualPremiumCents,
		arg.DwellingCoverageCents,
		arg.LiabilityCoverageCents,
		arg.DeductibleCents,
		arg.DocumentID,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Carrier,
		&i.PolicyNumberEnc,
		&i.Type,
		&i.AgentName,
		&i.AgentPhone,
		&i.AgentEmail,
		&i.EffectiveDate,
		&i.ExpirationDate,
		&i.AnnualPremiumCents,
		&i.DwellingCoverageCents,
		&i.LiabilityCoverageCents,
		&i.DeductibleCents,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInsurancePolicy = `-- name: DeleteInsurancePolicy :execrows
DELETE FROM insurance_policies WHERE id = ?
`

func (q *Queries) DeleteInsurancePolicy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInsurancePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findInsurancePolicy = `-- name: FindInsurancePolicy :one
SELECT id, property_id, carrier, policy_number_enc, type, agent_name, agent_phone, agent_email, effective_date, expiration_date, annual_premium_cents, dwelling_coverage_cents, liability_coverage_cents, deductible_cents, document_id, notes, created_at, updated_at FROM insurance_policies
WHERE property_id = ?1
  AND carrier = ?2
  AND policy_number_enc = ?3
LIMIT 1
`

type FindInsurancePolicyParams struct {
	PropertyID      int64
	Carrier         string
	PolicyNumberEnc string
}

// A carrier and a policy number identify a policy; the same declaration page
// forwarded twice is the same policy. The apply path reads this before it
// writes, the way the ingestion pipeline reads gmail_message_id.
func (q *Queries) FindInsurancePolicy(ctx context.Context, arg FindInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRowContext(ctx, findInsurancePolicy, arg.PropertyID, arg.Carrier, arg.PolicyNumberEnc)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Carrier,
		&i.PolicyNumberEnc,
		&i.Type,
		&i.AgentName,
		&i.AgentPhone,
		&i.AgentEmail,
		&i.EffectiveDate,
		&i.ExpirationDate,
		&i.AnnualPremiumCents,
		&i.DwellingCoverageCents,
		&i.LiabilityCoverageCents,
		&i.DeductibleCents,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInsurancePolicy = `-- name: GetInsurancePolicy :one
SELECT id, property_id, carrier, policy_number_enc, type, agent_name, agent_phone, agent_email, effective_date, expiration_date, annual_premium_cents, dwelling_coverage_cents, liability_coverage_cents, deductible_cents, document_id, notes, created_at, updated_at FROM insurance_policies WHERE id = ? LIMIT 1
`

func (q *Queries) GetInsurancePolicy(ctx context.Context, id int64) (InsurancePolicy, error) {
	row := q.db.QueryRowContext(ctx, getInsurancePolicy, id)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Carrier,
		&i.PolicyNumberEnc,
		&i.Type,
		&i.AgentName,
		&i.AgentPhone,
		&i.AgentEmail,
		&i.EffectiveDate,
		&i.ExpirationDate,
		&i.AnnualPremiumCents,
		&i.DwellingCoverageCents,
		&i.LiabilityCoverageCents,
		&i.DeductibleCents,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInsurancePoliciesByProperty = `-- name: ListInsurancePoliciesByProperty :many

SELECT id, property_id, carrier, policy_number_enc, type, agent_name, agent_phone, agent_email, effective_date, expiration_date, annual_premium_cents, dwelling_coverage_cents, liability_coverage_cents, deductible_cents, document_id, notes, created_at, updated_at FROM insurance_policies
WHERE property_id = ?
ORDER BY expiration_date DESC, id DESC
`

// Insurance policies, one property at a time.
//
// The policy number is stored encrypted and is decrypted at the one call site
// that has the key. Nothing here ever selects it for a list.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) ListInsurancePoliciesByProperty(ctx context.Context, propertyID int64) ([]InsurancePolicy, error) {
	rows, err := q.db.QueryContext(ctx, listInsurancePoliciesByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsurancePolicy{}
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Carrier,
			&i.PolicyNumberEnc,
			&i.Type,
			&i.AgentName,
			&i.AgentPhone,
			&i.AgentEmail,
			&i.EffectiveDate,
			&i.ExpirationDate,
			&i.AnnualPremiumCents,
			&i.DwellingCoverageCents,
			&i.LiabilityCoverageCents,
			&i.DeductibleCents,
			&i.DocumentID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsurancePolicy = `-- name: UpdateInsurancePolicy :one
UPDATE insurance_policies SET
    carrier                  = ?,
    policy_number_enc        = ?,
    type                     = ?,
    agent_name               = ?,
    agent_phone              = ?,
    agent_email              = ?,
    effective_date           = ?,
    expiration_date          = ?,
    annual_premium_cents     = ?,
    dwelling_coverage_cents  = ?,
    liability_coverage_cents = ?,
    deductible_cents         = ?,
    document_id              = ?,
    notes                    = ?,
    updated_at               = ?
WHERE id = ?
RETURNING id, property_id, carrier, policy_number_enc, type, agent_name, agent_phone, agent_email, effective_date, expiration_date, annual_premium_cents, dwelling_coverage_cents, liability_coverage_cents, deductible_cents, document_id, notes, created_at, updated_at
`

type UpdateInsurancePolicyParams struct {
	Carrier                string
	PolicyNumberEnc        string
	Type                   string
	AgentName              string
	AgentPhone             string
	AgentEmail             string
	EffectiveDate          *string
	ExpirationDate         *string
	AnnualPremiumCents     *domain.Money
	DwellingCoverageCents  *domain.Money
	LiabilityCoverageCents *domain.Money
	DeductibleCents        *domain.Money
	DocumentID             *int64
	Notes                  string
	UpdatedAt              string
	ID                     int64
}

// Every column is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateInsurancePolicy(ctx context.Context, arg UpdateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRowContext(ctx, updateInsurancePolicy,
		arg.Carrier,
		arg.PolicyNumberEnc,
		arg.Type,
		arg.AgentName,
		arg.AgentPhone,
		arg.AgentEmail,
		arg.EffectiveDate,
		arg.ExpirationDate,
		arg.AnnualPremiumCents,
		arg.DwellingCoverageCents,
		arg.LiabilityCoverageCents,
		arg.DeductibleCents,
		arg.DocumentID,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Carrier,
		&i.PolicyNumberEnc,
		&i.Type,
		&i.AgentName,
		&i.AgentPhone,
		&i.AgentEmail,
		&i.EffectiveDate,
		&i.ExpirationDate,
		&i.AnnualPremiumCents,
		&i.DwellingCoverageCents,
		&i.LiabilityCoverageCents,
		&i.DeductibleCents,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
