// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET
    status     = 'running',
    attempts   = attempts + 1,
    locked_at  = CAST(?1 AS TEXT),
    locked_by  = CAST(?2 AS TEXT),
    updated_at = ?1
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending' AND run_after <= ?1
    ORDER BY run_after, id
    LIMIT 1
)
RETURNING id, kind, payload, dedupe_key, run_after, attempts, max_attempts, locked_at, locked_by, last_error, status, created_at, updated_at
`

type ClaimJobParams struct {
	Now    string
	Worker string
}

// Claim exactly one runnable job and mark it running in the same statement.
//
// The inner SELECT picks the row and the UPDATE takes it, so two workers cannot
// both come away with the same job. Writes serialize on one connection anyway
// (docs/DESIGN.md section 2); this does not depend on that being true.
//
// attempts increments on claim rather than on failure, so a worker that is
// killed mid-job has still spent one of its tries. Otherwise a job that panics
// the process retries forever.
//
// The casts around the two arguments are load-bearing, the same way the ones in
// transactions.sql are: locked_at and locked_by are nullable columns, so
// without them sqlc infers both parameters nullable and hands the caller a
// *string for a value it always has.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.Now, arg.Worker)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs SET
    status     = 'done',
    locked_at  = NULL,
    locked_by  = NULL,
    last_error = '',
    updated_at = ?1
WHERE id = ?2
`

type CompleteJobParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.UpdatedAt, arg.ID)
	return err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, COUNT(*) AS count FROM jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string
	Count  int64
}

// Queue depth, for the status endpoint and the intake screen.
func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFinishedJobsBefore = `-- name: DeleteFinishedJobsBefore :execrows
DELETE FROM jobs WHERE status = 'done' AND updated_at < ?1
`

// Finished work is not history worth keeping forever; a failed job is.
func (q *Queries) DeleteFinishedJobsBefore(ctx context.Context, before string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFinishedJobsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (
    kind, payload, dedupe_key, run_after, max_attempts, status,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, kind, payload, dedupe_key, run_after, attempts, max_attempts, locked_at, locked_by, last_error, status, created_at, updated_at
`

type EnqueueJobParams struct {
	Kind        string
	Payload     string
	DedupeKey   *string
	RunAfter    string
	MaxAttempts int64
	CreatedAt   string
	UpdatedAt   string
}

// The job queue. A bounded worker pool drains it; see internal/jobs.
//
// Comments here are ASCII only, like every other query file: sqlc's SQLite
// rewriter counts comment offsets in runes and slices them in bytes.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.RunAfter,
		arg.MaxAttempts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET
    status     = 'failed',
    locked_at  = NULL,
    locked_by  = NULL,
    last_error = ?1,
    updated_at = ?2
WHERE id = ?3
`

type FailJobParams struct {
	LastError string
	UpdatedAt string
	ID        int64
}

// Out of attempts. The row stays as the record of what went wrong.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.UpdatedAt, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, dedupe_key, run_after, attempts, max_attempts, locked_at, locked_by, last_error, status, created_at, updated_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentFailedJobs = `-- name: ListRecentFailedJobs :many
SELECT id, kind, payload, dedupe_key, run_after, attempts, max_attempts, locked_at, locked_by, last_error, status, created_at, updated_at FROM jobs
WHERE status = 'failed'
ORDER BY updated_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListRecentFailedJobs(ctx context.Context, pageSize int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFailedJobs, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.DedupeKey,
			&i.RunAfter,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :execrows
UPDATE jobs SET
    status     = 'pending',
    locked_at  = NULL,
    locked_by  = NULL,
    last_error = 'reclaimed after the worker holding it stopped reporting',
    updated_at = ?1
WHERE status = 'running' AND locked_at < CAST(?2 AS TEXT)
`

type ReclaimStaleJobsParams struct {
	UpdatedAt string
	OlderThan string
}

// A job still locked past the lease belongs to a worker that is gone -- the
// process was killed, or the host rebooted mid-run. Returning it to pending is
// what stops that work being stranded until someone notices.
// Cast for the same reason ClaimJob casts: locked_at is nullable, and without
// it the cutoff arrives as a *string.
func (q *Queries) ReclaimStaleJobs(ctx context.Context, arg ReclaimStaleJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimStaleJobs, arg.UpdatedAt, arg.OlderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET
    status     = 'pending',
    run_after  = ?1,
    locked_at  = NULL,
    locked_by  = NULL,
    last_error = ?2,
    updated_at = ?3
WHERE id = ?4
`

type RetryJobParams struct {
	RunAfter  string
	LastError string
	UpdatedAt string
	ID        int64
}

// Back to pending with a later run_after: the caller computes the backoff.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob,
		arg.RunAfter,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
