// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package sqlc

import (
	"context"

	"github.com/farrellm/rental-bot/internal/domain"
)

const addLeaseTenant = `-- name: AddLeaseTenant :one
INSERT INTO lease_tenants (lease_id, tenant_id, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, lease_id, tenant_id, role, created_at, updated_at
`

type AddLeaseTenantParams struct {
	LeaseID   int64
	TenantID  int64
	Role      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) AddLeaseTenant(ctx context.Context, arg AddLeaseTenantParams) (LeaseTenant, error) {
	row := q.db.QueryRowContext(ctx, addLeaseTenant,
		arg.LeaseID,
		arg.TenantID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LeaseTenant
	err := row.Scan(
		&i.ID,
		&i.LeaseID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOverlappingLeases = `-- name: CountOverlappingLeases :one
SELECT CAST(COUNT(*) AS INTEGER) FROM leases
WHERE unit_id = ?1
  AND status IN ('pending', 'active')
  AND id <> ?2
  AND (CAST(?3 AS TEXT) IS NULL
       OR start_date <= CAST(?3 AS TEXT))
  AND (end_date IS NULL OR end_date >= ?4)
`

type CountOverlappingLeasesParams struct {
	UnitID    int64
	ExcludeID int64
	EndDate   *string
	StartDate *string
}

// Two active leases on one unit make occupancy ambiguous, and occupancy is
// derived rather than stored, so the write path is the only place that can
// keep it unambiguous. A null end_date is an open-ended tenancy and overlaps
// everything after its start.
func (q *Queries) CountOverlappingLeases(ctx context.Context, arg CountOverlappingLeasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOverlappingLeases,
		arg.UnitID,
		arg.ExcludeID,
		arg.EndDate,
		arg.StartDate,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLease = `-- name: CreateLease :one
INSERT INTO leases (
    unit_id, start_date, end_date, rent_cents, deposit_cents, due_day,
    late_fee_cents, status, renewal_of_lease_id, document_id, notes,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, unit_id, start_date, end_date, rent_cents, deposit_cents, due_day, late_fee_cents, status, renewal_of_lease_id, document_id, notes, created_at, updated_at
`

type CreateLeaseParams struct {
	UnitID           int64
	StartDate        string
	EndDate          *string
	RentCents        domain.Money
	DepositCents     *domain.Money
	DueDay           *int64
	LateFeeCents     *domain.Money
	Status           string
	RenewalOfLeaseID *int64
	DocumentID       *int64
	Notes            string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, createLease,
		arg.UnitID,
		arg.StartDate,
		arg.EndDate,
		arg.RentCents,
		arg.DepositCents,
		arg.DueDay,
		arg.LateFeeCents,
		arg.Status,
		arg.RenewalOfLeaseID,
		arg.DocumentID,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.StartDate,
		&i.EndDate,
		&i.RentCents,
		&i.DepositCents,
		&i.DueDay,
		&i.LateFeeCents,
		&i.Status,
		&i.RenewalOfLeaseID,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLease = `-- name: DeleteLease :execrows
DELETE FROM leases WHERE id = ?
`

func (q *Queries) DeleteLease(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLease = `-- name: GetLease :one
SELECT id, unit_id, start_date, end_date, rent_cents, deposit_cents, due_day, late_fee_cents, status, renewal_of_lease_id, document_id, notes, created_at, updated_at FROM leases WHERE id = ? LIMIT 1
`

func (q *Queries) GetLease(ctx context.Context, id int64) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLease, id)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.StartDate,
		&i.EndDate,
		&i.RentCents,
		&i.DepositCents,
		&i.DueDay,
		&i.LateFeeCents,
		&i.Status,
		&i.RenewalOfLeaseID,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaseWithUnit = `-- name: GetLeaseWithUnit :one
SELECT leases.id, leases.unit_id, leases.start_date, leases.end_date, leases.rent_cents, leases.deposit_cents, leases.due_day, leases.late_fee_cents, leases.status, leases.renewal_of_lease_id, leases.document_id, leases.notes, leases.created_at, leases.updated_at, units.label AS unit_label, units.property_id AS property_id
FROM leases
JOIN units ON units.id = leases.unit_id
WHERE leases.id = ?
LIMIT 1
`

type GetLeaseWithUnitRow struct {
	Lease      Lease
	UnitLabel  string
	PropertyID int64
}

func (q *Queries) GetLeaseWithUnit(ctx context.Context, id int64) (GetLeaseWithUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaseWithUnit, id)
	var i GetLeaseWithUnitRow
	err := row.Scan(
		&i.Lease.ID,
		&i.Lease.UnitID,
		&i.Lease.StartDate,
		&i.Lease.EndDate,
		&i.Lease.RentCents,
		&i.Lease.DepositCents,
		&i.Lease.DueDay,
		&i.Lease.LateFeeCents,
		&i.Lease.Status,
		&i.Lease.RenewalOfLeaseID,
		&i.Lease.DocumentID,
		&i.Lease.Notes,
		&i.Lease.CreatedAt,
		&i.Lease.UpdatedAt,
		&i.UnitLabel,
		&i.PropertyID,
	)
	return i, err
}

const listLeaseTenants = `-- name: ListLeaseTenants :many

SELECT tenants.id, tenants.name, tenants.email, tenants.phone, tenants.notes, tenants.created_at, tenants.updated_at, lease_tenants.role AS role
FROM lease_tenants
JOIN tenants ON tenants.id = lease_tenants.tenant_id
WHERE lease_tenants.lease_id = ?
ORDER BY lease_tenants.role, tenants.name
`

type ListLeaseTenantsRow struct {
	Tenant Tenant
	Role   string
}

// Who is on a lease ------------------------------------------------------
func (q *Queries) ListLeaseTenants(ctx context.Context, leaseID int64) ([]ListLeaseTenantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeaseTenants, leaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaseTenantsRow{}
	for rows.Next() {
		var i ListLeaseTenantsRow
		if err := rows.Scan(
			&i.Tenant.ID,
			&i.Tenant.Name,
			&i.Tenant.Email,
			&i.Tenant.Phone,
			&i.Tenant.Notes,
			&i.Tenant.CreatedAt,
			&i.Tenant.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesByProperty = `-- name: ListLeasesByProperty :many

SELECT leases.id, leases.unit_id, leases.start_date, leases.end_date, leases.rent_cents, leases.deposit_cents, leases.due_day, leases.late_fee_cents, leases.status, leases.renewal_of_lease_id, leases.document_id, leases.notes, leases.created_at, leases.updated_at, units.label AS unit_label
FROM leases
JOIN units ON units.id = leases.unit_id
WHERE units.property_id = ?1
ORDER BY leases.start_date DESC, leases.id DESC
`

type ListLeasesByPropertyRow struct {
	Lease     Lease
	UnitLabel string
}

// Every lease hangs off a unit, so a property's leases are reached through
// its units. The unit label rides along, because a lease reads as "Apt 2,
// 2026-01-01 to 2026-12-31" and a second query per row to learn the label
// would be a page of round trips.
func (q *Queries) ListLeasesByProperty(ctx context.Context, propertyID int64) ([]ListLeasesByPropertyRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeasesByPropertyRow{}
	for rows.Next() {
		var i ListLeasesByPropertyRow
		if err := rows.Scan(
			&i.Lease.ID,
			&i.Lease.UnitID,
			&i.Lease.StartDate,
			&i.Lease.EndDate,
			&i.Lease.RentCents,
			&i.Lease.DepositCents,
			&i.Lease.DueDay,
			&i.Lease.LateFeeCents,
			&i.Lease.Status,
			&i.Lease.RenewalOfLeaseID,
			&i.Lease.DocumentID,
			&i.Lease.Notes,
			&i.Lease.CreatedAt,
			&i.Lease.UpdatedAt,
			&i.UnitLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesByUnit = `-- name: ListLeasesByUnit :many
SELECT id, unit_id, start_date, end_date, rent_cents, deposit_cents, due_day, late_fee_cents, status, renewal_of_lease_id, document_id, notes, created_at, updated_at FROM leases WHERE unit_id = ? ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListLeasesByUnit(ctx context.Context, unitID int64) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.StartDate,
			&i.EndDate,
			&i.RentCents,
			&i.DepositCents,
			&i.DueDay,
			&i.LateFeeCents,
			&i.Status,
			&i.RenewalOfLeaseID,
			&i.DocumentID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLeaseTenant = `-- name: RemoveLeaseTenant :execrows
DELETE FROM lease_tenants
WHERE lease_id = ?1 AND tenant_id = ?2
`

type RemoveLeaseTenantParams struct {
	LeaseID  int64
	TenantID int64
}

func (q *Queries) RemoveLeaseTenant(ctx context.Context, arg RemoveLeaseTenantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeLeaseTenant, arg.LeaseID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLease = `-- name: UpdateLease :one
UPDATE leases SET
    unit_id             = ?,
    start_date          = ?,
    end_date            = ?,
    rent_cents          = ?,
    deposit_cents       = ?,
    due_day             = ?,
    late_fee_cents      = ?,
    status              = ?,
    renewal_of_lease_id = ?,
    document_id         = ?,
    notes               = ?,
    updated_at          = ?
WHERE id = ?
RETURNING id, unit_id, start_date, end_date, rent_cents, deposit_cents, due_day, late_fee_cents, status, renewal_of_lease_id, document_id, notes, created_at, updated_at
`

type UpdateLeaseParams struct {
	UnitID           int64
	StartDate        string
	EndDate          *string
	RentCents        domain.Money
	DepositCents     *domain.Money
	DueDay           *int64
	LateFeeCents     *domain.Money
	Status           string
	RenewalOfLeaseID *int64
	DocumentID       *int64
	Notes            string
	UpdatedAt        string
	ID               int64
}

// Every column is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateLease(ctx context.Context, arg UpdateLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, updateLease,
		arg.UnitID,
		arg.StartDate,
		arg.EndDate,
		arg.RentCents,
		arg.DepositCents,
		arg.DueDay,
		arg.LateFeeCents,
		arg.Status,
		arg.RenewalOfLeaseID,
		arg.DocumentID,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.StartDate,
		&i.EndDate,
		&i.RentCents,
		&i.DepositCents,
		&i.DueDay,
		&i.LateFeeCents,
		&i.Status,
		&i.RenewalOfLeaseID,
		&i.DocumentID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
