// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/farrellm/rental-bot/internal/domain"
)

type Document struct {
	ID               int64
	PropertyID       *int64
	Kind             string
	Title            string
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	Sha256           string
	StoragePath      string
	ExtractedText    string
	UploadedBy       *int64
	CreatedAt        string
	UpdatedAt        string
	SourceMessageID  *int64
}

type DocumentLink struct {
	ID         int64
	DocumentID int64
	EntityType string
	EntityID   int64
	CreatedAt  string
	UpdatedAt  string
}

type EmailAttachment struct {
	ID             int64
	EmailMessageID int64
	PartID         string
	Filename       string
	Mime           string
	SizeBytes      int64
	DocumentID     *int64
	SkippedReason  string
	CreatedAt      string
	UpdatedAt      string
}

type EmailMessage struct {
	ID             int64
	GmailMessageID string
	ThreadID       string
	FromAddr       string
	ToAddr         string
	Subject        string
	ReceivedAt     string
	Snippet        string
	RawPath        string
	Status         string
	Error          string
	CreatedAt      string
	UpdatedAt      string
}

type GmailAccount struct {
	ID              int64
	Address         string
	RefreshTokenEnc string
	Scopes          string
	ConnectedAt     string
	HistoryID       string
	WatchExpiresAt  *string
	LastSyncAt      *string
	LastSyncCount   int64
	LastError       string
	Status          string
	CreatedAt       string
	UpdatedAt       string
}

type Job struct {
	ID          int64
	Kind        string
	Payload     string
	DedupeKey   *string
	RunAfter    string
	Attempts    int64
	MaxAttempts int64
	LockedAt    *string
	LockedBy    *string
	LastError   string
	Status      string
	CreatedAt   string
	UpdatedAt   string
}

type Kv struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Lease struct {
	ID               int64
	UnitID           int64
	StartDate        string
	EndDate          *string
	RentCents        domain.Money
	DepositCents     *domain.Money
	DueDay           *int64
	LateFeeCents     *domain.Money
	Status           string
	RenewalOfLeaseID *int64
	DocumentID       *int64
	Notes            string
	CreatedAt        string
	UpdatedAt        string
}

type LeaseTenant struct {
	ID        int64
	LeaseID   int64
	TenantID  int64
	Role      string
	CreatedAt string
	UpdatedAt string
}

type Property struct {
	ID                 int64
	Nickname           string
	AddressLine1       string
	AddressLine2       string
	City               string
	State              string
	PostalCode         string
	County             string
	NormalizedAddress  string
	PurchaseDate       *string
	PurchasePriceCents *domain.Money
	Beds               *int64
	Baths              *float64
	Sqft               *int64
	YearBuilt          *int64
	Status             string
	Zpid               *string
	Notes              string
	CreatedAt          string
	UpdatedAt          string
}

type Repair struct {
	ID            int64
	PropertyID    int64
	UnitID        *int64
	OpenedOn      string
	ClosedOn      *string
	Status        string
	Category      string
	VendorID      *int64
	Description   string
	EstimateCents *domain.Money
	ActualCents   *domain.Money
	IsCapex       int64
	WarrantyUntil *string
	Notes         string
	CreatedAt     string
	UpdatedAt     string
}

type RepairEvent struct {
	ID         int64
	RepairID   int64
	At         string
	Note       string
	DocumentID *int64
	CreatedAt  string
	UpdatedAt  string
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	UserAgent  string
	Ip         string
	LastSeenAt string
	CreatedAt  string
	UpdatedAt  string
}

type Tenant struct {
	ID        int64
	Name      string
	Email     string
	Phone     string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

type Transaction struct {
	ID            int64
	PropertyID    int64
	OccurredOn    string
	AmountCents   domain.Money
	Category      string
	Description   string
	Counterparty  string
	PaymentMethod string
	UnitID        *int64
	LeaseID       *int64
	RepairID      *int64
	VendorID      *int64
	DocumentID    *int64
	Source        string
	Confidence    *float64
	NeedsReview   int64
	CreatedAt     string
	UpdatedAt     string
}

type Unit struct {
	ID         int64
	PropertyID int64
	Label      string
	Beds       *int64
	Baths      *float64
	Sqft       *int64
	CreatedAt  string
	UpdatedAt  string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	TotpSecret   *string
	CreatedAt    string
	UpdatedAt    string
}

type Vendor struct {
	ID        int64
	Name      string
	Trade     string
	Phone     string
	Email     string
	Notes     string
	CreatedAt string
	UpdatedAt string
}
