// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/farrellm/rental-bot/internal/domain"
)

type Job struct {
	ID          int64
	Kind        string
	Payload     string
	DedupeKey   *string
	RunAfter    string
	Attempts    int64
	MaxAttempts int64
	LockedAt    *string
	LockedBy    *string
	LastError   string
	Status      string
	CreatedAt   string
	UpdatedAt   string
}

type Kv struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Property struct {
	ID                 int64
	Nickname           string
	AddressLine1       string
	AddressLine2       string
	City               string
	State              string
	PostalCode         string
	County             string
	NormalizedAddress  string
	PurchaseDate       *string
	PurchasePriceCents *domain.Money
	Beds               *int64
	Baths              *float64
	Sqft               *int64
	YearBuilt          *int64
	Status             string
	Zpid               *string
	Notes              string
	CreatedAt          string
	UpdatedAt          string
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	UserAgent  string
	Ip         string
	LastSeenAt string
	CreatedAt  string
	UpdatedAt  string
}

type Unit struct {
	ID         int64
	PropertyID int64
	Label      string
	Beds       *int64
	Baths      *float64
	Sqft       *int64
	CreatedAt  string
	UpdatedAt  string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	TotpSecret   *string
	CreatedAt    string
	UpdatedAt    string
}
