// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mortgages.sql

package sqlc

import (
	"context"

	"github.com/farrellm/rental-bot/internal/domain"
)

const createMortgage = `-- name: CreateMortgage :one
INSERT INTO mortgages (
    property_id, lender, loan_number_enc, original_principal_cents,
    interest_rate_bps, term_months, origination_date, monthly_pi_cents,
    escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date,
    notes, created_at, updated_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, property_id, lender, loan_number_enc, original_principal_cents, interest_rate_bps, term_months, origination_date, monthly_pi_cents, escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date, notes, created_at, updated_at
`

type CreateMortgageParams struct {
	PropertyID             int64
	Lender                 string
	LoanNumberEnc          string
	OriginalPrincipalCents *domain.Money
	InterestRateBps        *int64
	TermMonths             *int64
	OriginationDate        *string
	MonthlyPiCents         *domain.Money
	EscrowMonthlyCents     *domain.Money
	CurrentBalanceCents    *domain.Money
	BalanceAsOf            *string
	PayoffDate             *string
	Notes                  string
	CreatedAt              string
	UpdatedAt              string
}

func (q *Queries) CreateMortgage(ctx context.Context, arg CreateMortgageParams) (Mortgage, error) {
	row := q.db.QueryRowContext(ctx, createMortgage,
		arg.PropertyID,
		arg.Lender,
		arg.LoanNumberEnc,
		arg.OriginalPrincipalCents,
		arg.InterestRateBps,
		arg.TermMonths,
		arg.OriginationDate,
		arg.MonthlyPiCents,
		arg.EscrowMonthlyCents,
		arg.CurrentBalanceCents,
		arg.BalanceAsOf,
		arg.PayoffDate,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Mortgage
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Lender,
		&i.LoanNumberEnc,
		&i.OriginalPrincipalCents,
		&i.InterestRateBps,
		&i.TermMonths,
		&i.OriginationDate,
		&i.MonthlyPiCents,
		&i.EscrowMonthlyCents,
		&i.CurrentBalanceCents,
		&i.BalanceAsOf,
		&i.PayoffDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMortgageStatement = `-- name: CreateMortgageStatement :one
INSERT INTO mortgage_statements (
    mortgage_id, statement_date, principal_balance_cents, payment_cents,
    principal_paid_cents, interest_paid_cents, escrow_paid_cents,
    document_id, created_at, updated_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?
)
RETURNING id, mortgage_id, statement_date, principal_balance_cents, payment_cents, principal_paid_cents, interest_paid_cents, escrow_paid_cents, document_id, created_at, updated_at
`

type CreateMortgageStatementParams struct {
	MortgageID            int64
	StatementDate         string
	PrincipalBalanceCents *domain.Money
	PaymentCents          *domain.Money
	PrincipalPaidCents    *domain.Money
	InterestPaidCents     *domain.Money
	EscrowPaidCents       *domain.Money
	DocumentID            *int64
	CreatedAt             string
	UpdatedAt             string
}

func (q *Queries) CreateMortgageStatement(ctx context.Context, arg CreateMortgageStatementParams) (MortgageStatement, error) {
	row := q.db.QueryRowContext(ctx, createMortgageStatement,
		arg.MortgageID,
		arg.StatementDate,
		arg.PrincipalBalanceCents,
		arg.PaymentCents,
		arg.PrincipalPaidCents,
		arg.InterestPaidCents,
		arg.EscrowPaidCents,
		arg.DocumentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MortgageStatement
	err := row.Scan(
		&i.ID,
		&i.MortgageID,
		&i.StatementDate,
		&i.PrincipalBalanceCents,
		&i.PaymentCents,
		&i.PrincipalPaidCents,
		&i.InterestPaidCents,
		&i.EscrowPaidCents,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMortgage = `-- name: DeleteMortgage :execrows
DELETE FROM mortgages WHERE id = ?
`

func (q *Queries) DeleteMortgage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMortgage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findMortgageByLender = `-- name: FindMortgageByLender :one
SELECT id, property_id, lender, loan_number_enc, original_principal_cents, interest_rate_bps, term_months, origination_date, monthly_pi_cents, escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date, notes, created_at, updated_at FROM mortgages
WHERE property_id = ?1 AND lender = ?2
ORDER BY id
LIMIT 1
`

type FindMortgageByLenderParams struct {
	PropertyID int64
	Lender     string
}

// A property usually has one mortgage, and a statement names its lender rather
// than an id. Matching on the lender is what turns the second into the first.
func (q *Queries) FindMortgageByLender(ctx context.Context, arg FindMortgageByLenderParams) (Mortgage, error) {
	row := q.db.QueryRowContext(ctx, findMortgageByLender, arg.PropertyID, arg.Lender)
	var i Mortgage
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Lender,
		&i.LoanNumberEnc,
		&i.OriginalPrincipalCents,
		&i.InterestRateBps,
		&i.TermMonths,
		&i.OriginationDate,
		&i.MonthlyPiCents,
		&i.EscrowMonthlyCents,
		&i.CurrentBalanceCents,
		&i.BalanceAsOf,
		&i.PayoffDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMortgage = `-- name: GetMortgage :one
SELECT id, property_id, lender, loan_number_enc, original_principal_cents, interest_rate_bps, term_months, origination_date, monthly_pi_cents, escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date, notes, created_at, updated_at FROM mortgages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMortgage(ctx context.Context, id int64) (Mortgage, error) {
	row := q.db.QueryRowContext(ctx, getMortgage, id)
	var i Mortgage
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Lender,
		&i.LoanNumberEnc,
		&i.OriginalPrincipalCents,
		&i.InterestRateBps,
		&i.TermMonths,
		&i.OriginationDate,
		&i.MonthlyPiCents,
		&i.EscrowMonthlyCents,
		&i.CurrentBalanceCents,
		&i.BalanceAsOf,
		&i.PayoffDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMortgageStatement = `-- name: GetMortgageStatement :one
SELECT id, mortgage_id, statement_date, principal_balance_cents, payment_cents, principal_paid_cents, interest_paid_cents, escrow_paid_cents, document_id, created_at, updated_at FROM mortgage_statements WHERE id = ? LIMIT 1
`

func (q *Queries) GetMortgageStatement(ctx context.Context, id int64) (MortgageStatement, error) {
	row := q.db.QueryRowContext(ctx, getMortgageStatement, id)
	var i MortgageStatement
	err := row.Scan(
		&i.ID,
		&i.MortgageID,
		&i.StatementDate,
		&i.PrincipalBalanceCents,
		&i.PaymentCents,
		&i.PrincipalPaidCents,
		&i.InterestPaidCents,
		&i.EscrowPaidCents,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMortgageStatements = `-- name: ListMortgageStatements :many

SELECT id, mortgage_id, statement_date, principal_balance_cents, payment_cents, principal_paid_cents, interest_paid_cents, escrow_paid_cents, document_id, created_at, updated_at FROM mortgage_statements
WHERE mortgage_id = ?
ORDER BY statement_date DESC, id DESC
`

// Statements ----------------------------------------------------------------
func (q *Queries) ListMortgageStatements(ctx context.Context, mortgageID int64) ([]MortgageStatement, error) {
	rows, err := q.db.QueryContext(ctx, listMortgageStatements, mortgageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MortgageStatement{}
	for rows.Next() {
		var i MortgageStatement
		if err := rows.Scan(
			&i.ID,
			&i.MortgageID,
			&i.StatementDate,
			&i.PrincipalBalanceCents,
			&i.PaymentCents,
			&i.PrincipalPaidCents,
			&i.InterestPaidCents,
			&i.EscrowPaidCents,
			&i.DocumentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMortgagesByProperty = `-- name: ListMortgagesByProperty :many

SELECT id, property_id, lender, loan_number_enc, original_principal_cents, interest_rate_bps, term_months, origination_date, monthly_pi_cents, escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date, notes, created_at, updated_at FROM mortgages
WHERE property_id = ?
ORDER BY origination_date DESC, id DESC
`

// Mortgages, and the statements that arrive against them.
//
// A statement is append-only, which is what makes the amortization history a
// consequence of the write path rather than a feature to build. The UNIQUE on
// (mortgage_id, statement_date) is the idempotency key an apply reads before
// it writes: the same statement forwarded twice is one statement.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) ListMortgagesByProperty(ctx context.Context, propertyID int64) ([]Mortgage, error) {
	rows, err := q.db.QueryContext(ctx, listMortgagesByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mortgage{}
	for rows.Next() {
		var i Mortgage
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Lender,
			&i.LoanNumberEnc,
			&i.OriginalPrincipalCents,
			&i.InterestRateBps,
			&i.TermMonths,
			&i.OriginationDate,
			&i.MonthlyPiCents,
			&i.EscrowMonthlyCents,
			&i.CurrentBalanceCents,
			&i.BalanceAsOf,
			&i.PayoffDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMortgageBalance = `-- name: SetMortgageBalance :exec
UPDATE mortgages SET
    current_balance_cents = ?1,
    balance_as_of         = ?2,
    updated_at            = ?3
WHERE id = ?4
  AND (balance_as_of IS NULL OR balance_as_of <= ?2)
`

type SetMortgageBalanceParams struct {
	CurrentBalanceCents *domain.Money
	BalanceAsOf         *string
	UpdatedAt           string
	ID                  int64
}

// The running balance, taken off the statement that carried it. It is a
// separate write from the statement insert so that a statement out of order
// cannot walk the balance backwards.
func (q *Queries) SetMortgageBalance(ctx context.Context, arg SetMortgageBalanceParams) error {
	_, err := q.db.ExecContext(ctx, setMortgageBalance,
		arg.CurrentBalanceCents,
		arg.BalanceAsOf,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMortgage = `-- name: UpdateMortgage :one
UPDATE mortgages SET
    lender                   = ?,
    loan_number_enc          = ?,
    original_principal_cents = ?,
    interest_rate_bps        = ?,
    term_months              = ?,
    origination_date         = ?,
    monthly_pi_cents         = ?,
    escrow_monthly_cents     = ?,
    current_balance_cents    = ?,
    balance_as_of            = ?,
    payoff_date              = ?,
    notes                    = ?,
    updated_at               = ?
WHERE id = ?
RETURNING id, property_id, lender, loan_number_enc, original_principal_cents, interest_rate_bps, term_months, origination_date, monthly_pi_cents, escrow_monthly_cents, current_balance_cents, balance_as_of, payoff_date, notes, created_at, updated_at
`

type UpdateMortgageParams struct {
	Lender                 string
	LoanNumberEnc          string
	OriginalPrincipalCents *domain.Money
	InterestRateBps        *int64
	TermMonths             *int64
	OriginationDate        *string
	MonthlyPiCents         *domain.Money
	EscrowMonthlyCents     *domain.Money
	CurrentBalanceCents    *domain.Money
	BalanceAsOf            *string
	PayoffDate             *string
	Notes                  string
	UpdatedAt              string
	ID                     int64
}

// Every column is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateMortgage(ctx context.Context, arg UpdateMortgageParams) (Mortgage, error) {
	row := q.db.QueryRowContext(ctx, updateMortgage,
		arg.Lender,
		arg.LoanNumberEnc,
		arg.OriginalPrincipalCents,
		arg.InterestRateBps,
		arg.TermMonths,
		arg.OriginationDate,
		arg.MonthlyPiCents,
		arg.EscrowMonthlyCents,
		arg.CurrentBalanceCents,
		arg.BalanceAsOf,
		arg.PayoffDate,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Mortgage
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Lender,
		&i.LoanNumberEnc,
		&i.OriginalPrincipalCents,
		&i.InterestRateBps,
		&i.TermMonths,
		&i.OriginationDate,
		&i.MonthlyPiCents,
		&i.EscrowMonthlyCents,
		&i.CurrentBalanceCents,
		&i.BalanceAsOf,
		&i.PayoffDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
