// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
)

const countChannelNotifications = `-- name: CountChannelNotifications :one
SELECT
    COUNT(*) AS total,
    COUNT(CASE WHEN resolved_at IS NULL THEN 1 END) AS outstanding
FROM notifications
WHERE channel = ?
`

type CountChannelNotificationsRow struct {
	Total       int64
	Outstanding int64
}

func (q *Queries) CountChannelNotifications(ctx context.Context, channel string) (CountChannelNotificationsRow, error) {
	row := q.db.QueryRowContext(ctx, countChannelNotifications, channel)
	var i CountChannelNotificationsRow
	err := row.Scan(&i.Total, &i.Outstanding)
	return i, err
}

const countNotifications = `-- name: CountNotifications :one
SELECT
    COUNT(*) AS total,
    COUNT(CASE WHEN resolved_at IS NULL THEN 1 END) AS outstanding
FROM notifications
`

type CountNotificationsRow struct {
	Total       int64
	Outstanding int64
}

// The foot of the dispatch card: how much the register holds without counting
// the lines. COUNT rather than SUM over a CASE, because SUM of no rows is NULL
// and a tally of nothing is zero.
func (q *Queries) CountNotifications(ctx context.Context) (CountNotificationsRow, error) {
	row := q.db.QueryRowContext(ctx, countNotifications)
	var i CountNotificationsRow
	err := row.Scan(&i.Total, &i.Outstanding)
	return i, err
}

const getOpenNotification = `-- name: GetOpenNotification :one

SELECT id, dedupe_key, channel, severity, title, detail, first_seen_at, last_sent_at, send_count, resolved_at, created_at, updated_at FROM notifications
WHERE dedupe_key = ? AND channel = ? AND resolved_at IS NULL
LIMIT 1
`

type GetOpenNotificationParams struct {
	DedupeKey string
	Channel   string
}

// The delivery log: what went out, when, and how many times.
//
// One open row per condition per channel, enforced by the partial unique index
// in 0004. Everything here follows from that: the bus looks for the open row,
// and either inserts, restates, or stays quiet. A row is never written twice
// for the same condition, which is what makes a flapping condition send once
// and then go silent (docs/DESIGN.md section 8.3).
//
// Comments here are ASCII only, like every other query file.
// The condition as it currently stands, or nothing when it is not outstanding.
func (q *Queries) GetOpenNotification(ctx context.Context, arg GetOpenNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getOpenNotification, arg.DedupeKey, arg.Channel)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.Channel,
		&i.Severity,
		&i.Title,
		&i.Detail,
		&i.FirstSeenAt,
		&i.LastSentAt,
		&i.SendCount,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    dedupe_key, channel, severity, title, detail,
    first_seen_at, last_sent_at, send_count, resolved_at,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, NULL, 0, NULL,
    ?, ?
)
RETURNING id, dedupe_key, channel, severity, title, detail, first_seen_at, last_sent_at, send_count, resolved_at, created_at, updated_at
`

type InsertNotificationParams struct {
	DedupeKey   string
	Channel     string
	Severity    string
	Title       string
	Detail      string
	FirstSeenAt string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.DedupeKey,
		arg.Channel,
		arg.Severity,
		arg.Title,
		arg.Detail,
		arg.FirstSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.Channel,
		&i.Severity,
		&i.Title,
		&i.Detail,
		&i.FirstSeenAt,
		&i.LastSentAt,
		&i.SendCount,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelNotificationsAfter = `-- name: ListChannelNotificationsAfter :many
SELECT id, dedupe_key, channel, severity, title, detail, first_seen_at, last_sent_at, send_count, resolved_at, created_at, updated_at FROM notifications
WHERE channel = ?1
  AND ((first_seen_at < ?2)
    OR (first_seen_at = ?2 AND id < ?3))
ORDER BY first_seen_at DESC, id DESC
LIMIT ?4
`

type ListChannelNotificationsAfterParams struct {
	Channel          string
	AfterFirstSeenAt string
	AfterID          int64
	PageSize         int64
}

func (q *Queries) ListChannelNotificationsAfter(ctx context.Context, arg ListChannelNotificationsAfterParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listChannelNotificationsAfter,
		arg.Channel,
		arg.AfterFirstSeenAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.Channel,
			&i.Severity,
			&i.Title,
			&i.Detail,
			&i.FirstSeenAt,
			&i.LastSentAt,
			&i.SendCount,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelNotificationsFirstPage = `-- name: ListChannelNotificationsFirstPage :many
SELECT id, dedupe_key, channel, severity, title, detail, first_seen_at, last_sent_at, send_count, resolved_at, created_at, updated_at FROM notifications
WHERE channel = ?
ORDER BY first_seen_at DESC, id DESC
LIMIT ?
`

type ListChannelNotificationsFirstPageParams struct {
	Channel string
	Limit   int64
}

// The register, newest first, for one channel.
//
// Every subscribed channel gets its own row per condition, because each has its
// own cooldown and its own delivery. That is right for the record and wrong for
// a screen: with a bot configured the operator would read every condition
// twice, once for the channel it went out on and once for the log. So the
// register is always read one channel at a time.
//
// Keyset pagination on first_seen_at with id breaking the tie, the same shape
// every other list in this schema uses.
func (q *Queries) ListChannelNotificationsFirstPage(ctx context.Context, arg ListChannelNotificationsFirstPageParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listChannelNotificationsFirstPage, arg.Channel, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.Channel,
			&i.Severity,
			&i.Title,
			&i.Detail,
			&i.FirstSeenAt,
			&i.LastSentAt,
			&i.SendCount,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNotificationSent = `-- name: RecordNotificationSent :exec
UPDATE notifications SET
    last_sent_at = CAST(?1 AS TEXT),
    send_count   = send_count + 1,
    severity     = ?2,
    title        = ?3,
    detail       = ?4,
    updated_at   = ?5
WHERE id = ?6
`

type RecordNotificationSentParams struct {
	LastSentAt string
	Severity   string
	Title      string
	Detail     string
	UpdatedAt  string
	ID         int64
}

// A restatement: the same condition, said again after its cooldown. The tally
// in the margin of the dispatch register is this column.
func (q *Queries) RecordNotificationSent(ctx context.Context, arg RecordNotificationSentParams) error {
	_, err := q.db.ExecContext(ctx, recordNotificationSent,
		arg.LastSentAt,
		arg.Severity,
		arg.Title,
		arg.Detail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const resolveNotification = `-- name: ResolveNotification :execrows
UPDATE notifications SET
    resolved_at = CAST(?1 AS TEXT),
    updated_at  = ?2
WHERE dedupe_key = ?3
  AND channel = ?4
  AND resolved_at IS NULL
`

type ResolveNotificationParams struct {
	ResolvedAt string
	UpdatedAt  string
	DedupeKey  string
	Channel    string
}

// Closing a condition. execrows is what tells the caller whether there was
// anything to close, and therefore whether a recovery message is owed -- a
// probe calls this on every sweep, and only the sweep that finds an open row
// should say anything.
func (q *Queries) ResolveNotification(ctx context.Context, arg ResolveNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveNotification,
		arg.ResolvedAt,
		arg.UpdatedAt,
		arg.DedupeKey,
		arg.Channel,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
