// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package sqlc

import (
	"context"

	"github.com/farrellm/rental-bot/internal/domain"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
    nickname, address_line1, address_line2, city, state, postal_code, county,
    normalized_address, purchase_date, purchase_price_cents, beds, baths,
    sqft, year_built, status, zpid, notes, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, nickname, address_line1, address_line2, city, state, postal_code, county, normalized_address, purchase_date, purchase_price_cents, beds, baths, sqft, year_built, status, zpid, notes, created_at, updated_at
`

type CreatePropertyParams struct {
	Nickname           string
	AddressLine1       string
	AddressLine2       string
	City               string
	State              string
	PostalCode         string
	County             string
	NormalizedAddress  string
	PurchaseDate       *string
	PurchasePriceCents *domain.Money
	Beds               *int64
	Baths              *float64
	Sqft               *int64
	YearBuilt          *int64
	Status             string
	Zpid               *string
	Notes              string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.Nickname,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.County,
		arg.NormalizedAddress,
		arg.PurchaseDate,
		arg.PurchasePriceCents,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.YearBuilt,
		arg.Status,
		arg.Zpid,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.County,
		&i.NormalizedAddress,
		&i.PurchaseDate,
		&i.PurchasePriceCents,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.YearBuilt,
		&i.Status,
		&i.Zpid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProperty = `-- name: DeleteProperty :execrows
DELETE FROM properties WHERE id = ?
`

func (q *Queries) DeleteProperty(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProperty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProperty = `-- name: GetProperty :one
SELECT id, nickname, address_line1, address_line2, city, state, postal_code, county, normalized_address, purchase_date, purchase_price_cents, beds, baths, sqft, year_built, status, zpid, notes, created_at, updated_at FROM properties WHERE id = ? LIMIT 1
`

func (q *Queries) GetProperty(ctx context.Context, id int64) (Property, error) {
	row := q.db.QueryRowContext(ctx, getProperty, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.County,
		&i.NormalizedAddress,
		&i.PurchaseDate,
		&i.PurchasePriceCents,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.YearBuilt,
		&i.Status,
		&i.Zpid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPropertiesAfter = `-- name: ListPropertiesAfter :many
SELECT
    properties.id, properties.nickname, properties.address_line1, properties.address_line2, properties.city, properties.state, properties.postal_code, properties.county, properties.normalized_address, properties.purchase_date, properties.purchase_price_cents, properties.beds, properties.baths, properties.sqft, properties.year_built, properties.status, properties.zpid, properties.notes, properties.created_at, properties.updated_at,
    (SELECT COUNT(*) FROM units WHERE units.property_id = properties.id) AS unit_count
FROM properties
WHERE properties.nickname > ?1
   OR (properties.nickname = ?1 AND properties.id > ?2)
ORDER BY properties.nickname, properties.id
LIMIT ?3
`

type ListPropertiesAfterParams struct {
	AfterNickname string
	AfterID       int64
	PageSize      int64
}

type ListPropertiesAfterRow struct {
	Property  Property
	UnitCount int64
}

func (q *Queries) ListPropertiesAfter(ctx context.Context, arg ListPropertiesAfterParams) ([]ListPropertiesAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesAfter, arg.AfterNickname, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesAfterRow{}
	for rows.Next() {
		var i ListPropertiesAfterRow
		if err := rows.Scan(
			&i.Property.ID,
			&i.Property.Nickname,
			&i.Property.AddressLine1,
			&i.Property.AddressLine2,
			&i.Property.City,
			&i.Property.State,
			&i.Property.PostalCode,
			&i.Property.County,
			&i.Property.NormalizedAddress,
			&i.Property.PurchaseDate,
			&i.Property.PurchasePriceCents,
			&i.Property.Beds,
			&i.Property.Baths,
			&i.Property.Sqft,
			&i.Property.YearBuilt,
			&i.Property.Status,
			&i.Property.Zpid,
			&i.Property.Notes,
			&i.Property.CreatedAt,
			&i.Property.UpdatedAt,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesFirstPage = `-- name: ListPropertiesFirstPage :many

SELECT
    properties.id, properties.nickname, properties.address_line1, properties.address_line2, properties.city, properties.state, properties.postal_code, properties.county, properties.normalized_address, properties.purchase_date, properties.purchase_price_cents, properties.beds, properties.baths, properties.sqft, properties.year_built, properties.status, properties.zpid, properties.notes, properties.created_at, properties.updated_at,
    (SELECT COUNT(*) FROM units WHERE units.property_id = properties.id) AS unit_count
FROM properties
ORDER BY properties.nickname, properties.id
LIMIT ?
`

type ListPropertiesFirstPageRow struct {
	Property  Property
	UnitCount int64
}

// Listing carries the unit count as a correlated subquery rather than a
// second round trip per row: the index screen shows it on every card.
//
// Pagination is a keyset over (nickname, id), which is also the sort order.
// nickname is not unique, so id breaks the tie and keeps the cursor stable
// when two properties share a name.
func (q *Queries) ListPropertiesFirstPage(ctx context.Context, limit int64) ([]ListPropertiesFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesFirstPageRow{}
	for rows.Next() {
		var i ListPropertiesFirstPageRow
		if err := rows.Scan(
			&i.Property.ID,
			&i.Property.Nickname,
			&i.Property.AddressLine1,
			&i.Property.AddressLine2,
			&i.Property.City,
			&i.Property.State,
			&i.Property.PostalCode,
			&i.Property.County,
			&i.Property.NormalizedAddress,
			&i.Property.PurchaseDate,
			&i.Property.PurchasePriceCents,
			&i.Property.Beds,
			&i.Property.Baths,
			&i.Property.Sqft,
			&i.Property.YearBuilt,
			&i.Property.Status,
			&i.Property.Zpid,
			&i.Property.Notes,
			&i.Property.CreatedAt,
			&i.Property.UpdatedAt,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertyMatchKeys = `-- name: ListPropertyMatchKeys :many
SELECT id, nickname, normalized_address FROM properties
ORDER BY id
`

type ListPropertyMatchKeysRow struct {
	ID                int64
	Nickname          string
	NormalizedAddress string
}

// Everything the property matcher needs and nothing else.
//
// The comparison is deterministic Go over the folded address (docs/DESIGN.md
// section 5.3), not SQL, because "close enough" is an edit distance and SQLite
// cannot spell one. The portfolio is tens of rows, so loading all of them and
// comparing in memory is cheaper than the index that would let the database
// try.
func (q *Queries) ListPropertyMatchKeys(ctx context.Context) ([]ListPropertyMatchKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertyMatchKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertyMatchKeysRow{}
	for rows.Next() {
		var i ListPropertyMatchKeysRow
		if err := rows.Scan(&i.ID, &i.Nickname, &i.NormalizedAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties SET
    nickname             = ?,
    address_line1        = ?,
    address_line2        = ?,
    city                 = ?,
    state                = ?,
    postal_code          = ?,
    county               = ?,
    normalized_address   = ?,
    purchase_date        = ?,
    purchase_price_cents = ?,
    beds                 = ?,
    baths                = ?,
    sqft                 = ?,
    year_built           = ?,
    status               = ?,
    zpid                 = ?,
    notes                = ?,
    updated_at           = ?
WHERE id = ?
RETURNING id, nickname, address_line1, address_line2, city, state, postal_code, county, normalized_address, purchase_date, purchase_price_cents, beds, baths, sqft, year_built, status, zpid, notes, created_at, updated_at
`

type UpdatePropertyParams struct {
	Nickname           string
	AddressLine1       string
	AddressLine2       string
	City               string
	State              string
	PostalCode         string
	County             string
	NormalizedAddress  string
	PurchaseDate       *string
	PurchasePriceCents *domain.Money
	Beds               *int64
	Baths              *float64
	Sqft               *int64
	YearBuilt          *int64
	Status             string
	Zpid               *string
	Notes              string
	UpdatedAt          string
	ID                 int64
}

// Every column is written, because PATCH is applied as a read-modify-write in
// Go rather than as a pile of COALESCE clauses. A nullable column has three
// states on the wire (absent, null, and set) and COALESCE cannot express the
// difference between the first two. Read-modify-write is safe here because the
// writer pool is a single connection by design.
func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, updateProperty,
		arg.Nickname,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.County,
		arg.NormalizedAddress,
		arg.PurchaseDate,
		arg.PurchasePriceCents,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.YearBuilt,
		arg.Status,
		arg.Zpid,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.County,
		&i.NormalizedAddress,
		&i.PurchaseDate,
		&i.PurchasePriceCents,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.YearBuilt,
		&i.Status,
		&i.Zpid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
