// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposals.sql

package sqlc

import (
	"context"
)

const countProposalsByStatus = `-- name: CountProposalsByStatus :many
SELECT status, COUNT(*) AS count FROM ingest_proposals GROUP BY status
`

type CountProposalsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountProposalsByStatus(ctx context.Context) ([]CountProposalsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countProposalsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProposalsByStatusRow{}
	for rows.Next() {
		var i CountProposalsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProposal = `-- name: CreateProposal :one
INSERT INTO ingest_proposals (
    email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens,
    confidence, property_hint, property_id, reasoning, status,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at
`

type CreateProposalParams struct {
	EmailMessageID   int64
	Kind             string
	Payload          string
	LlmModel         string
	PromptTokens     int64
	CompletionTokens int64
	Confidence       *float64
	PropertyHint     string
	PropertyID       *int64
	Reasoning        string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, createProposal,
		arg.EmailMessageID,
		arg.Kind,
		arg.Payload,
		arg.LlmModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Confidence,
		arg.PropertyHint,
		arg.PropertyID,
		arg.Reasoning,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one

SELECT id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at FROM ingest_proposals WHERE id = ? LIMIT 1
`

// The proposal gate: what a model claimed, before anybody agreed to it.
//
// A row is written at classify time and enriched at extract time, so the two
// stages are an insert and an update rather than two tables. Nothing here reads
// into payload; it is opaque JSON whose shape the Go struct fixes.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) GetProposal(ctx context.Context, id int64) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, getProposal, id)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposalByMessage = `-- name: GetProposalByMessage :one
SELECT id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at FROM ingest_proposals
WHERE email_message_id = ?
ORDER BY id DESC
LIMIT 1
`

// The pipeline reads this before it enqueues, so re-running a classify for a
// message that already has a proposal writes nothing. That read is what makes
// the sweep free to walk the same messages the direct enqueue already covered.
func (q *Queries) GetProposalByMessage(ctx context.Context, emailMessageID int64) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, getProposalByMessage, emailMessageID)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessagesAwaitingProposal = `-- name: ListMessagesAwaitingProposal :many
SELECT email_messages.id, email_messages.gmail_message_id, email_messages.thread_id, email_messages.from_addr, email_messages.to_addr, email_messages.subject, email_messages.received_at, email_messages.snippet, email_messages.raw_path, email_messages.status, email_messages.error, email_messages.created_at, email_messages.updated_at FROM email_messages
LEFT JOIN ingest_proposals ON ingest_proposals.email_message_id = email_messages.id
WHERE email_messages.status = 'received'
  AND ingest_proposals.id IS NULL
ORDER BY email_messages.received_at, email_messages.id
LIMIT ?1
`

// Every message that arrived, was allowed through, and has no proposal against
// it. This is what the sweep walks: the direct enqueue at sync time makes
// ingestion fast, and this makes it reliable.
func (q *Queries) ListMessagesAwaitingProposal(ctx context.Context, pageSize int64) ([]EmailMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAwaitingProposal, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailMessage{}
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.GmailMessageID,
			&i.ThreadID,
			&i.FromAddr,
			&i.ToAddr,
			&i.Subject,
			&i.ReceivedAt,
			&i.Snippet,
			&i.RawPath,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsAfter = `-- name: ListProposalsAfter :many
SELECT id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at FROM ingest_proposals
WHERE (CAST(?1 AS TEXT) IS NULL
       OR status = CAST(?1 AS TEXT))
  AND (created_at < ?2
       OR (created_at = ?2 AND id < ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListProposalsAfterParams struct {
	Status         *string
	AfterCreatedAt string
	AfterID        int64
	PageSize       int64
}

func (q *Queries) ListProposalsAfter(ctx context.Context, arg ListProposalsAfterParams) ([]IngestProposal, error) {
	rows, err := q.db.QueryContext(ctx, listProposalsAfter,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestProposal{}
	for rows.Next() {
		var i IngestProposal
		if err := rows.Scan(
			&i.ID,
			&i.EmailMessageID,
			&i.Kind,
			&i.Payload,
			&i.LlmModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Confidence,
			&i.PropertyHint,
			&i.PropertyID,
			&i.Reasoning,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.AppliedEntityType,
			&i.AppliedEntityID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsFirstPage = `-- name: ListProposalsFirstPage :many
SELECT id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at FROM ingest_proposals
WHERE (CAST(?1 AS TEXT) IS NULL
       OR status = CAST(?1 AS TEXT))
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListProposalsFirstPageParams struct {
	Status   *string
	PageSize int64
}

// The review queue, newest first. The keyset runs backwards over
// (created_at, id): two proposals can share a second, and id breaks the tie.
// A NULL status filter drops out of the WHERE clause, and the CAST around it
// is load-bearing -- without it sqlc's inference types the parameter
// interface{} rather than *string.
func (q *Queries) ListProposalsFirstPage(ctx context.Context, arg ListProposalsFirstPageParams) ([]IngestProposal, error) {
	rows, err := q.db.QueryContext(ctx, listProposalsFirstPage, arg.Status, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestProposal{}
	for rows.Next() {
		var i IngestProposal
		if err := rows.Scan(
			&i.ID,
			&i.EmailMessageID,
			&i.Kind,
			&i.Payload,
			&i.LlmModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Confidence,
			&i.PropertyHint,
			&i.PropertyID,
			&i.Reasoning,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.AppliedEntityType,
			&i.AppliedEntityID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProposalExtract = `-- name: RecordProposalExtract :one
UPDATE ingest_proposals SET
    payload           = ?1,
    llm_model         = ?2,
    prompt_tokens     = prompt_tokens + ?3,
    completion_tokens = completion_tokens + ?4,
    confidence        = ?5,
    property_id       = ?6,
    error             = ?7,
    updated_at        = ?8
WHERE id = ?9
RETURNING id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at
`

type RecordProposalExtractParams struct {
	Payload          string
	LlmModel         string
	PromptTokens     int64
	CompletionTokens int64
	Confidence       *float64
	PropertyID       *int64
	Error            string
	UpdatedAt        string
	ID               int64
}

// What the extract stage learned. The token counts are added to rather than
// replaced, because classify already spent some and the sum is what the budget
// breaker reads.
func (q *Queries) RecordProposalExtract(ctx context.Context, arg RecordProposalExtractParams) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, recordProposalExtract,
		arg.Payload,
		arg.LlmModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Confidence,
		arg.PropertyID,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProposalError = `-- name: SetProposalError :exec
UPDATE ingest_proposals SET
    error      = ?1,
    updated_at = ?2
WHERE id = ?3
`

type SetProposalErrorParams struct {
	Error     string
	UpdatedAt string
	ID        int64
}

// An apply that could not go through. The proposal stays pending -- the
// operator has something to fix and try again -- and the reason rides on the
// row so the screen can say what rather than only that.
func (q *Queries) SetProposalError(ctx context.Context, arg SetProposalErrorParams) error {
	_, err := q.db.ExecContext(ctx, setProposalError, arg.Error, arg.UpdatedAt, arg.ID)
	return err
}

const settleProposal = `-- name: SettleProposal :one
UPDATE ingest_proposals SET
    status              = ?1,
    reviewed_by         = ?2,
    reviewed_at         = ?3,
    applied_entity_type = ?4,
    applied_entity_id   = ?5,
    error               = ?6,
    updated_at          = ?7
WHERE id = ?8 AND status = 'pending'
RETURNING id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at
`

type SettleProposalParams struct {
	Status            string
	ReviewedBy        *int64
	ReviewedAt        *string
	AppliedEntityType *string
	AppliedEntityID   *int64
	Error             string
	UpdatedAt         string
	ID                int64
}

// The transition, guarded in the statement rather than in Go.
//
// A proposal leaves 'pending' exactly once. Two approvals arriving together
// would both pass a read-then-write, and the second would file the receipt a
// second time; the WHERE clause is what makes the loser see zero rows. This is
// the discipline PairTelegram follows, for the same reason.
func (q *Queries) SettleProposal(ctx context.Context, arg SettleProposalParams) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, settleProposal,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.AppliedEntityType,
		arg.AppliedEntityID,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumProposalTokensSince = `-- name: SumProposalTokensSince :one
SELECT CAST(COALESCE(SUM(prompt_tokens + completion_tokens), 0) AS INTEGER)
FROM ingest_proposals
WHERE created_at >= ?1
`

// The budget breaker's ledger. Every call the pipeline makes lands on a
// proposal row, so one sum over a month is the whole spend. The CAST is what
// makes sqlc type this int64 rather than interface{}.
func (q *Queries) SumProposalTokensSince(ctx context.Context, since string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumProposalTokensSince, since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProposal = `-- name: UpdateProposal :one
UPDATE ingest_proposals SET
    kind        = ?1,
    payload     = ?2,
    property_id = ?3,
    updated_at  = ?4
WHERE id = ?5
RETURNING id, email_message_id, kind, payload, llm_model, prompt_tokens, completion_tokens, confidence, property_hint, property_id, reasoning, status, reviewed_by, reviewed_at, applied_entity_type, applied_entity_id, error, created_at, updated_at
`

type UpdateProposalParams struct {
	Kind       string
	Payload    string
	PropertyID *int64
	UpdatedAt  string
	ID         int64
}

// Correcting a proposal before approving it. Every column the operator can
// touch is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateProposal(ctx context.Context, arg UpdateProposalParams) (IngestProposal, error) {
	row := q.db.QueryRowContext(ctx, updateProposal,
		arg.Kind,
		arg.Payload,
		arg.PropertyID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IngestProposal
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Kind,
		&i.Payload,
		&i.LlmModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Confidence,
		&i.PropertyHint,
		&i.PropertyID,
		&i.Reasoning,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedEntityType,
		&i.AppliedEntityID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
