// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, token_hash, expires_at, user_agent, ip, last_seen_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, token_hash, expires_at, user_agent, ip, last_seen_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	UserAgent  string
	Ip         string
	LastSeenAt string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?
`

// Sessions outlive their usefulness silently, so something has to sweep them.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.expires_at, sessions.user_agent, sessions.ip, sessions.last_seen_at, sessions.created_at, sessions.updated_at, users.id, users.username, users.email, users.password_hash, users.totp_secret, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = ?
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	Session Session
	User    User
}

// The session and its user in one read: every authenticated request needs
// both, and this lookup is on the hot path for all of them.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.Session.LastSeenAt,
		&i.Session.CreatedAt,
		&i.Session.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.TotpSecret,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = ?, expires_at = ?, updated_at = ?
WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt string
	ExpiresAt  string
	UpdatedAt  string
	ID         int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
