// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package sqlc

import (
	"context"
)

const deleteTelegramState = `-- name: DeleteTelegramState :execrows
DELETE FROM telegram_state WHERE id = 1
`

// Unpairing is server access only (section 8.2). It drops the whole row rather
// than nulling the chat, because a half-cleared pairing is a state nothing else
// in this file knows how to read.
func (q *Queries) DeleteTelegramState(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTelegramState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureTelegramState = `-- name: EnsureTelegramState :exec
INSERT INTO telegram_state (
    id, chat_id, last_update_id, muted_until, paired_at,
    pairing_code_hash, pairing_expires_at, last_sent_at, last_error, status,
    created_at, updated_at
) VALUES (
    1, NULL, 0, NULL, NULL,
    '', NULL, NULL, '', 'unpaired',
    ?, ?
)
ON CONFLICT (id) DO NOTHING
`

type EnsureTelegramStateParams struct {
	CreatedAt string
	UpdatedAt string
}

// The row is created before anything is stored in it, so every narrow UPDATE
// below has something to update. Issuing a pairing code is the first thing
// that happens to a fresh install, and it should not also have to know how to
// create the row.
func (q *Queries) EnsureTelegramState(ctx context.Context, arg EnsureTelegramStateParams) error {
	_, err := q.db.ExecContext(ctx, ensureTelegramState, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const getTelegramState = `-- name: GetTelegramState :one

SELECT id, chat_id, last_update_id, muted_until, paired_at, pairing_code_hash, pairing_expires_at, last_sent_at, last_error, status, created_at, updated_at FROM telegram_state WHERE id = 1 LIMIT 1
`

// The Telegram channel: one row, id 1.
//
// The writes are narrow on purpose, like gmail.sql's. Pairing, the long-poll
// cursor, a mute, a delivery and a failure each touch only the columns they
// know about, so a send that lands while a mute is being set cannot roll back
// the muted_until it never read.
//
// Comments here are ASCII only, like every other query file.
func (q *Queries) GetTelegramState(ctx context.Context) (TelegramState, error) {
	row := q.db.QueryRowContext(ctx, getTelegramState)
	var i TelegramState
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.LastUpdateID,
		&i.MutedUntil,
		&i.PairedAt,
		&i.PairingCodeHash,
		&i.PairingExpiresAt,
		&i.LastSentAt,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pairTelegram = `-- name: PairTelegram :execrows
UPDATE telegram_state SET
    chat_id            = CAST(?1 AS INTEGER),
    paired_at          = CAST(?2 AS TEXT),
    pairing_code_hash  = '',
    pairing_expires_at = NULL,
    last_error         = '',
    status             = 'paired',
    updated_at         = ?3
WHERE id = 1
  AND chat_id IS NULL
  AND pairing_code_hash = ?4
  AND pairing_expires_at IS NOT NULL
  AND pairing_expires_at > CAST(?5 AS TEXT)
`

type PairTelegramParams struct {
	ChatID          int64
	PairedAt        string
	UpdatedAt       string
	PairingCodeHash string
	Now             string
}

// Pairing consumes the code: the hash and its expiry are cleared in the same
// statement that stores the chat, so a captured code cannot be replayed against
// a second chat.
//
// The guard in the WHERE clause is what makes this single-use even when two
// updates arrive at once. A caller reads execrows to find out whether it won.
// The casts are the ones CLAUDE.md warns about: chat_id, paired_at and
// pairing_expires_at are all nullable columns, and without them sqlc types the
// parameters as pointers to values the caller can never not have.
func (q *Queries) PairTelegram(ctx context.Context, arg PairTelegramParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pairTelegram,
		arg.ChatID,
		arg.PairedAt,
		arg.UpdatedAt,
		arg.PairingCodeHash,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordTelegramSent = `-- name: RecordTelegramSent :exec
UPDATE telegram_state SET
    last_sent_at = CAST(?1 AS TEXT),
    last_error   = '',
    status       = 'paired',
    updated_at   = ?2
WHERE id = 1
`

type RecordTelegramSentParams struct {
	LastSentAt string
	UpdatedAt  string
}

// A delivery that lands clears the degradation in the same statement, the way
// SetGmailCursor does. Recovery costs no second write and cannot be forgotten.
func (q *Queries) RecordTelegramSent(ctx context.Context, arg RecordTelegramSentParams) error {
	_, err := q.db.ExecContext(ctx, recordTelegramSent, arg.LastSentAt, arg.UpdatedAt)
	return err
}

const setTelegramCursor = `-- name: SetTelegramCursor :exec
UPDATE telegram_state SET
    last_update_id = ?1,
    updated_at     = ?2
WHERE id = 1
`

type SetTelegramCursorParams struct {
	LastUpdateID int64
	UpdatedAt    string
}

func (q *Queries) SetTelegramCursor(ctx context.Context, arg SetTelegramCursorParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramCursor, arg.LastUpdateID, arg.UpdatedAt)
	return err
}

const setTelegramMute = `-- name: SetTelegramMute :exec
UPDATE telegram_state SET
    muted_until = ?1,
    updated_at  = ?2
WHERE id = 1
`

type SetTelegramMuteParams struct {
	MutedUntil *string
	UpdatedAt  string
}

// muted_until keeps its pointer: not muted is a real state, and NULL is how it
// is spelled.
func (q *Queries) SetTelegramMute(ctx context.Context, arg SetTelegramMuteParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramMute, arg.MutedUntil, arg.UpdatedAt)
	return err
}

const setTelegramPairingCode = `-- name: SetTelegramPairingCode :exec
UPDATE telegram_state SET
    pairing_code_hash  = ?1,
    pairing_expires_at = CAST(?2 AS TEXT),
    updated_at         = ?3
WHERE id = 1
`

type SetTelegramPairingCodeParams struct {
	PairingCodeHash  string
	PairingExpiresAt string
	UpdatedAt        string
}

// Only the hash is stored. The code itself is shown once, in the log and on the
// intake screen, and is never recoverable from the database.
func (q *Queries) SetTelegramPairingCode(ctx context.Context, arg SetTelegramPairingCodeParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramPairingCode, arg.PairingCodeHash, arg.PairingExpiresAt, arg.UpdatedAt)
	return err
}

const setTelegramStatus = `-- name: SetTelegramStatus :exec
UPDATE telegram_state SET
    status     = ?1,
    last_error = ?2,
    updated_at = ?3
WHERE id = 1
`

type SetTelegramStatusParams struct {
	Status    string
	LastError string
	UpdatedAt string
}

// degraded is recoverable and is not fatal to the process: the last known state
// stays on the card, annotated with what went wrong.
func (q *Queries) SetTelegramStatus(ctx context.Context, arg SetTelegramStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramStatus, arg.Status, arg.LastError, arg.UpdatedAt)
	return err
}
