// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, email, phone, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, email, phone, notes, created_at, updated_at
`

type CreateTenantParams struct {
	Name      string
	Email     string
	Phone     string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants WHERE id = ?
`

func (q *Queries) DeleteTenant(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, email, phone, notes, created_at, updated_at FROM tenants WHERE id = ? LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, email, phone, notes, created_at, updated_at FROM tenants ORDER BY name, id
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET
    name       = ?,
    email      = ?,
    phone      = ?,
    notes      = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, email, phone, notes, created_at, updated_at
`

type UpdateTenantParams struct {
	Name      string
	Email     string
	Phone     string
	Notes     string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
