// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/farrellm/rental-bot/internal/domain"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    property_id, occurred_on, amount_cents, category, description,
    counterparty, payment_method, unit_id, lease_id, repair_id,
    vendor_id, document_id, source, confidence, needs_review,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, property_id, occurred_on, amount_cents, category, description, counterparty, payment_method, unit_id, lease_id, repair_id, vendor_id, document_id, source, confidence, needs_review, created_at, updated_at
`

type CreateTransactionParams struct {
	PropertyID    int64
	OccurredOn    string
	AmountCents   domain.Money
	Category      string
	Description   string
	Counterparty  string
	PaymentMethod string
	UnitID        *int64
	LeaseID       *int64
	RepairID      *int64
	VendorID      *int64
	DocumentID    *int64
	Source        string
	Confidence    *float64
	NeedsReview   int64
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.PropertyID,
		arg.OccurredOn,
		arg.AmountCents,
		arg.Category,
		arg.Description,
		arg.Counterparty,
		arg.PaymentMethod,
		arg.UnitID,
		arg.LeaseID,
		arg.RepairID,
		arg.VendorID,
		arg.DocumentID,
		arg.Source,
		arg.Confidence,
		arg.NeedsReview,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.OccurredOn,
		&i.AmountCents,
		&i.Category,
		&i.Description,
		&i.Counterparty,
		&i.PaymentMethod,
		&i.UnitID,
		&i.LeaseID,
		&i.RepairID,
		&i.VendorID,
		&i.DocumentID,
		&i.Source,
		&i.Confidence,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, property_id, occurred_on, amount_cents, category, description, counterparty, payment_method, unit_id, lease_id, repair_id, vendor_id, document_id, source, confidence, needs_review, created_at, updated_at FROM transactions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.OccurredOn,
		&i.AmountCents,
		&i.Category,
		&i.Description,
		&i.Counterparty,
		&i.PaymentMethod,
		&i.UnitID,
		&i.LeaseID,
		&i.RepairID,
		&i.VendorID,
		&i.DocumentID,
		&i.Source,
		&i.Confidence,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsAfter = `-- name: ListTransactionsAfter :many
SELECT id, property_id, occurred_on, amount_cents, category, description, counterparty, payment_method, unit_id, lease_id, repair_id, vendor_id, document_id, source, confidence, needs_review, created_at, updated_at FROM transactions
WHERE property_id = ?1
  AND (CAST(?2 AS TEXT) IS NULL
       OR occurred_on >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) IS NULL
       OR occurred_on <= CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) IS NULL
       OR category = CAST(?4 AS TEXT))
  AND (occurred_on < ?5
       OR (occurred_on = ?5 AND id < ?6))
ORDER BY occurred_on DESC, id DESC
LIMIT ?7
`

type ListTransactionsAfterParams struct {
	PropertyID int64
	FromDate   *string
	ToDate     *string
	Category   *string
	AfterDate  string
	AfterID    int64
	PageSize   int64
}

func (q *Queries) ListTransactionsAfter(ctx context.Context, arg ListTransactionsAfterParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsAfter,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
		arg.Category,
		arg.AfterDate,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.OccurredOn,
			&i.AmountCents,
			&i.Category,
			&i.Description,
			&i.Counterparty,
			&i.PaymentMethod,
			&i.UnitID,
			&i.LeaseID,
			&i.RepairID,
			&i.VendorID,
			&i.DocumentID,
			&i.Source,
			&i.Confidence,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFirstPage = `-- name: ListTransactionsFirstPage :many

SELECT id, property_id, occurred_on, amount_cents, category, description, counterparty, payment_method, unit_id, lease_id, repair_id, vendor_id, document_id, source, confidence, needs_review, created_at, updated_at FROM transactions
WHERE property_id = ?1
  AND (CAST(?2 AS TEXT) IS NULL
       OR occurred_on >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) IS NULL
       OR occurred_on <= CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) IS NULL
       OR category = CAST(?4 AS TEXT))
ORDER BY occurred_on DESC, id DESC
LIMIT ?5
`

type ListTransactionsFirstPageParams struct {
	PropertyID int64
	FromDate   *string
	ToDate     *string
	Category   *string
	PageSize   int64
}

// The ledger, newest entry first. The keyset runs backwards over
// (occurred_on, id), because a day holds more than one entry and the date
// alone would skip or repeat rows at a page boundary.
//
// The three filters are optional in one query rather than eight: sqlc.narg
// makes each a nullable parameter, and a NULL one drops out of the WHERE
// clause. The totals query repeats the same predicate, so a filtered page and
// its totals always describe the same set of rows.
//
// The CAST around each narg is load-bearing, not noise. Without it sqlc's
// SQLite inference gives up and types the parameter as interface{}, which
// lets a call site pass anything at all; with it the parameter is *string and
// a wrong type is a compile error. Do not remove them.
func (q *Queries) ListTransactionsFirstPage(ctx context.Context, arg ListTransactionsFirstPageParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsFirstPage,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
		arg.Category,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.OccurredOn,
			&i.AmountCents,
			&i.Category,
			&i.Description,
			&i.Counterparty,
			&i.PaymentMethod,
			&i.UnitID,
			&i.LeaseID,
			&i.RepairID,
			&i.VendorID,
			&i.DocumentID,
			&i.Source,
			&i.Confidence,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactions = `-- name: SumTransactions :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN amount_cents > 0 THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS income_cents,
    CAST(COALESCE(SUM(CASE WHEN amount_cents < 0 THEN amount_cents ELSE 0 END), 0) AS INTEGER) AS expense_cents,
    CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER) AS net_cents,
    CAST(COUNT(*) AS INTEGER) AS entry_count
FROM transactions
WHERE property_id = ?1
  AND (CAST(?2 AS TEXT) IS NULL
       OR occurred_on >= CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) IS NULL
       OR occurred_on <= CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) IS NULL
       OR category = CAST(?4 AS TEXT))
`

type SumTransactionsParams struct {
	PropertyID int64
	FromDate   *string
	ToDate     *string
	Category   *string
}

type SumTransactionsRow struct {
	IncomeCents  int64
	ExpenseCents int64
	NetCents     int64
	EntryCount   int64
}

// The foot of the ledger sheet. Income and expense are the same signed column
// split by sign, and the net is their sum, so the three can never disagree.
// The CAST is also what makes sqlc type these as int64 rather than interface{}.
func (q *Queries) SumTransactions(ctx context.Context, arg SumTransactionsParams) (SumTransactionsRow, error) {
	row := q.db.QueryRowContext(ctx, sumTransactions,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
		arg.Category,
	)
	var i SumTransactionsRow
	err := row.Scan(
		&i.IncomeCents,
		&i.ExpenseCents,
		&i.NetCents,
		&i.EntryCount,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET
    occurred_on    = ?,
    amount_cents   = ?,
    category       = ?,
    description    = ?,
    counterparty   = ?,
    payment_method = ?,
    unit_id        = ?,
    lease_id       = ?,
    repair_id      = ?,
    vendor_id      = ?,
    document_id    = ?,
    needs_review   = ?,
    updated_at     = ?
WHERE id = ?
RETURNING id, property_id, occurred_on, amount_cents, category, description, counterparty, payment_method, unit_id, lease_id, repair_id, vendor_id, document_id, source, confidence, needs_review, created_at, updated_at
`

type UpdateTransactionParams struct {
	OccurredOn    string
	AmountCents   domain.Money
	Category      string
	Description   string
	Counterparty  string
	PaymentMethod string
	UnitID        *int64
	LeaseID       *int64
	RepairID      *int64
	VendorID      *int64
	DocumentID    *int64
	NeedsReview   int64
	UpdatedAt     string
	ID            int64
}

// Every column is written, because PATCH is a read-modify-write in Go.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.OccurredOn,
		arg.AmountCents,
		arg.Category,
		arg.Description,
		arg.Counterparty,
		arg.PaymentMethod,
		arg.UnitID,
		arg.LeaseID,
		arg.RepairID,
		arg.VendorID,
		arg.DocumentID,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.OccurredOn,
		&i.AmountCents,
		&i.Category,
		&i.Description,
		&i.Counterparty,
		&i.PaymentMethod,
		&i.UnitID,
		&i.LeaseID,
		&i.RepairID,
		&i.VendorID,
		&i.DocumentID,
		&i.Source,
		&i.Confidence,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
