// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const countUnitsByProperty = `-- name: CountUnitsByProperty :one
SELECT COUNT(*) FROM units WHERE property_id = ?
`

// Guards the invariant that every lease hangs off a unit (DESIGN.md 3.2):
// a property can never be left with zero units.
func (q *Queries) CountUnitsByProperty(ctx context.Context, propertyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnitsByProperty, propertyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (property_id, label, beds, baths, sqft, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, property_id, label, beds, baths, sqft, created_at, updated_at
`

type CreateUnitParams struct {
	PropertyID int64
	Label      string
	Beds       *int64
	Baths      *float64
	Sqft       *int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.PropertyID,
		arg.Label,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :execrows
DELETE FROM units WHERE id = ?
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUnit = `-- name: GetUnit :one
SELECT id, property_id, label, beds, baths, sqft, created_at, updated_at FROM units WHERE id = ? LIMIT 1
`

func (q *Queries) GetUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnitsByProperty = `-- name: ListUnitsByProperty :many
SELECT id, property_id, label, beds, baths, sqft, created_at, updated_at FROM units WHERE property_id = ? ORDER BY label, id
`

func (q *Queries) ListUnitsByProperty(ctx context.Context, propertyID int64) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Label,
			&i.Beds,
			&i.Baths,
			&i.Sqft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units SET
    label      = ?,
    beds       = ?,
    baths      = ?,
    sqft       = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, property_id, label, beds, baths, sqft, created_at, updated_at
`

type UpdateUnitParams struct {
	Label     string
	Beds      *int64
	Baths     *float64
	Sqft      *int64
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, updateUnit,
		arg.Label,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
