// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const countUnitsByProperty = `-- name: CountUnitsByProperty :one
SELECT COUNT(*) FROM units WHERE property_id = ?
`

// Guards the invariant that every lease hangs off a unit (DESIGN.md 3.2):
// a property can never be left with zero units.
func (q *Queries) CountUnitsByProperty(ctx context.Context, propertyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnitsByProperty, propertyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (property_id, label, beds, baths, sqft, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, property_id, label, beds, baths, sqft, created_at, updated_at
`

type CreateUnitParams struct {
	PropertyID int64
	Label      string
	Beds       *int64
	Baths      *float64
	Sqft       *int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.PropertyID,
		arg.Label,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :execrows
DELETE FROM units WHERE id = ?
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUnit = `-- name: GetUnit :one
SELECT id, property_id, label, beds, baths, sqft, created_at, updated_at FROM units WHERE id = ? LIMIT 1
`

func (q *Queries) GetUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnitsByProperty = `-- name: ListUnitsByProperty :many
SELECT id, property_id, label, beds, baths, sqft, created_at, updated_at FROM units WHERE property_id = ? ORDER BY label, id
`

func (q *Queries) ListUnitsByProperty(ctx context.Context, propertyID int64) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Label,
			&i.Beds,
			&i.Baths,
			&i.Sqft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsWithOccupancy = `-- name: ListUnitsWithOccupancy :many
SELECT
    units.id, units.property_id, units.label, units.beds, units.baths, units.sqft, units.created_at, units.updated_at,
    leases.id AS active_lease_id,
    leases.end_date AS active_lease_end_date
FROM units
LEFT JOIN leases ON leases.unit_id = units.id
    AND leases.status = 'active'
    AND leases.start_date <= ?1
    AND (leases.end_date IS NULL OR leases.end_date >= ?1)
WHERE units.property_id = ?2
ORDER BY units.label, units.id
`

type ListUnitsWithOccupancyParams struct {
	Today      string
	PropertyID int64
}

type ListUnitsWithOccupancyRow struct {
	Unit               Unit
	ActiveLeaseID      *int64
	ActiveLeaseEndDate *string
}

// Occupancy is derived, never stored (DESIGN.md 3.2): a unit is occupied if it
// has an active lease covering today. There is no is_occupied column to drift
// out of sync with the leases that are the actual evidence, so the answer is
// recomputed on every read from the dates themselves.
//
// The join carries the lease id rather than a flag, so the screen can link to
// the lease that is the reason for the answer. It is a LEFT JOIN because most
// units on most days have no active lease, and that is not a missing row.
func (q *Queries) ListUnitsWithOccupancy(ctx context.Context, arg ListUnitsWithOccupancyParams) ([]ListUnitsWithOccupancyRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsWithOccupancy, arg.Today, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsWithOccupancyRow{}
	for rows.Next() {
		var i ListUnitsWithOccupancyRow
		if err := rows.Scan(
			&i.Unit.ID,
			&i.Unit.PropertyID,
			&i.Unit.Label,
			&i.Unit.Beds,
			&i.Unit.Baths,
			&i.Unit.Sqft,
			&i.Unit.CreatedAt,
			&i.Unit.UpdatedAt,
			&i.ActiveLeaseID,
			&i.ActiveLeaseEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units SET
    label      = ?,
    beds       = ?,
    baths      = ?,
    sqft       = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, property_id, label, beds, baths, sqft, created_at, updated_at
`

type UpdateUnitParams struct {
	Label     string
	Beds      *int64
	Baths     *float64
	Sqft      *int64
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, updateUnit,
		arg.Label,
		arg.Beds,
		arg.Baths,
		arg.Sqft,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Label,
		&i.Beds,
		&i.Baths,
		&i.Sqft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
