// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, totp_secret, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, username, email, password_hash, totp_secret, created_at, updated_at FROM users WHERE username = ? LIMIT 1
`

// Comments in this directory are ASCII only. sqlc's SQLite rewriter counts
// comment offsets in runes but slices them in bytes, so a single multi-byte
// character silently corrupts the query that follows it: one em dash turns
// "RETURNING *" into "RETURNIN". See sqlc.yaml.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (username, email, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (username) DO UPDATE SET
    password_hash = excluded.password_hash,
    updated_at    = excluded.updated_at
RETURNING id, username, email, password_hash, totp_secret, created_at, updated_at
`

type UpsertUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

// Used by `rental-bot -create-user`, which is the only way a user is ever
// created; there is no registration endpoint. Re-running it for an existing
// username resets that user's password rather than failing, so an operator
// who has locked themselves out has a way back in.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
