// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package sqlc

import (
	"context"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (name, trade, phone, email, notes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, trade, phone, email, notes, created_at, updated_at
`

type CreateVendorParams struct {
	Name      string
	Trade     string
	Phone     string
	Email     string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, createVendor,
		arg.Name,
		arg.Trade,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trade,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :execrows
DELETE FROM vendors WHERE id = ?
`

func (q *Queries) DeleteVendor(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVendor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVendor = `-- name: GetVendor :one
SELECT id, name, trade, phone, email, notes, created_at, updated_at FROM vendors WHERE id = ? LIMIT 1
`

func (q *Queries) GetVendor(ctx context.Context, id int64) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendor, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trade,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, name, trade, phone, email, notes, created_at, updated_at FROM vendors ORDER BY name, id
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Trade,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors SET
    name       = ?,
    trade      = ?,
    phone      = ?,
    email      = ?,
    notes      = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, trade, phone, email, notes, created_at, updated_at
`

type UpdateVendorParams struct {
	Name      string
	Trade     string
	Phone     string
	Email     string
	Notes     string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, updateVendor,
		arg.Name,
		arg.Trade,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trade,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
